CREATE TABLE "CAUSEWAYEXTSECMAN"."APPLICATIONPERMISSION"
(
    "ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
    "FEATUREFQN" VARCHAR2(255) NOT NULL ENABLE,
    "FEATURESORT" VARCHAR2(255) NOT NULL ENABLE,
    "MODE" VARCHAR2(255) NOT NULL ENABLE,
    "ROLEID" NUMBER NOT NULL ENABLE,
    "RULE" VARCHAR2(255) NOT NULL ENABLE,
    "VERSION" NUMBER NOT NULL ENABLE,
    CONSTRAINT "APPLICATIONPERMISSION_PK" PRIMARY KEY ("ID")
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
        STORAGE (
            INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
            BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
        )
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
;

GRANT select, insert, update, delete  on CAUSEWAYEXTSECMAN.APPLICATIONPERMISSION TO ITGUSR;
