--------------------------------------------------------
--  File creato - giovedì-febbraio-26-2026   
--------------------------------------------------------
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\ADSAPPLICAZIONI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\ADSSERVIZITECNICI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\AMBIENTESDLC.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\AMMINISTRATOREDISISTEMA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\APPLICAZIONE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\APPLICAZIONESA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\APPLICAZIONIAMBIENTISDLC.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\APPLICAZIONICOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\APPLICAZIONIDATIPERSONALI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\APPLICAZIONISERVIZITECNICI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\APPLICAZIONIVERSIONI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\AREAAPPLICATIVA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\ATTIVITA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\ATTIVITAUTENTI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\CATEGORIADATI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\CATEGORIAINTERESSATI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\CONTESTOAPPLICATIVO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\CONTRATTO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\CONTRATTOAPP.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\DATABASE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\DATABASEAPPCOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\DATABASESERVTECNCOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\DATODADB.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\DATODADBRIGHETESTO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\FUNZIONESA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\GRUPPIMEMBRI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\GRUPPO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\IDENTITA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\PIATTAFAPPCOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\PIATTAFORMA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\PIATTAFSERVTECNCOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\RECORDOFPROCESSINGACTIVITY.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\RESPONSABILEAPPLICATIVO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\ROPARIGHETESTO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\RUOLIFUNZIONISA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\RUOLOSA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\SERVER.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\SERVIZIOTECNICO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\SERVIZITECNICIAMBIENTISDLC.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\SERVIZITECNICIAPP.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\SERVIZITECNICICOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\SERVIZITECNICIENDPOINTS.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\SERVIZITECNICISERVTEC.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\SERVIZITECNICIVERSIONI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TABELLADBDATIPERSONALI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\SHARE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TECHDATABASE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TECNOLOGIASW.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TECNOLOGIASWSERVIZI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOAPPLICAZIONE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOASSET.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOAUTENTICAZIONE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOAUTORIZZAZIONE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOCOMPONENTE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOCOMPONENTESERVIZI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPODATABASE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOENDPOINT.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOGRUPPO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOFRUIZIONE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOIDENTITA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOINDICE3.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOINFRASTRUTTURAASUPP.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOINSTALLAZIONESUDISP.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOPROCESSINGACTIVITY.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOSCM.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOSDL1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOSDL2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOSDL3.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOSERVIZIOTECNICO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOSICUREZZA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOSSO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOUTENTE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOUTENTETECNICO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\TIPOUTENZADIDATABASE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\UNITAORGANIZZATIVA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\TABLES\UTENTE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ADSAPPLICAZIONI_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ADSAPPLICAZIONI_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ADSAPPLICAZIONI_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ADSAPPLICAZIONI_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ADSSERVIZITECNICI_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ADSSERVIZITECNICI_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ADSSERVIZITECNICI_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ADSSERVIZITECNICI_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\AMBIENTESDLC_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\AMBIENTESDLC_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\AMBIENTESDLC_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ADS_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\AMMINISTRATOREDISISTEMA_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\AMMINISTRATOREDISISTEMA_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_NOME_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N56.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N55.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N54.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N53.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N59.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N58.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N57.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N70.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N52.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N51.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N73.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N72.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N71.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N67.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N66.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N65.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N64.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N69.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N68.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N63.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N62.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N61.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_N60.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\UNIQUE_DESC_TEST.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONE_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICASIONESA_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONESA_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONESA_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONIAMBIENTISDLC_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONIAMBIENTISDLC_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONIAMBIENTISDLC_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONIAMBIENTISDLC_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONICOMPARCH_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONICOMPARCH_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONICOMPARCH_N51.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONICOMPARCH_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONICOMPARCH_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONIDATIPERSONALI_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONIDATIPERSONALI_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONIDATIPERSONALI_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONIDATIPERSONALI_N51.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONIDATIPERSONALI_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONISERVIZITECNICI_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONISERVIZITECNICI_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONISERVIZITECNICI_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONISERVIZITECNICI_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONIVERSIONI_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONIVERSIONI_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\APPLICAZIONIVERSIONI_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\AREAAPPLICATIVA_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\AREAAPPLICATIVA_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\AREAAPPLICATIVA_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ATTIVITA_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ATTIVITA_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ATTIVITA_N51.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ATTIVITA_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ATTIVITA_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ATTIVITAUTENTI_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ATTIVITAUTENTI_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ATTIVITAUTENTI_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ATTIVITAUTENTI_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CATEGORIADATI_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CATEGORIADATI_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CATEGORIADATI_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CATEGORIAINTERESSATI_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CATEGORIAINTERESSATI_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CATEGORIAINTERESSATI_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CONTESTOAPPLICATIVO_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CONTESTOAPPLICATIVO_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CONTESTOAPPLICATIVO_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CONTRATTO_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CONTRATTO_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CONTRATTOAPP_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CONTRATTIAPPLICAIZONI_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CONTRATTOAPP_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\CONTRATTOAPP_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATABASE_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATABASES_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATABASE_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATABASE_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATABASE_N51.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATABASEAPPCOMPARCH_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATABASEAPPCOMPARCH_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATABASEAPPCOMPARCH_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATABASEAPPCOMPARCH_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATABASESERVTECNCOMPARCH_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATABASESERVTECNCOMPARCH_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATABASESERVTECNCOMPARCH_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATABASESERVTECNCOMPARCH_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATODADB_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATODADBRIGHETESTO_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\DATODADBRIGHETESTO_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\FUNZIONESA_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\FUNZIONESA_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\FUNZIONESA_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\FUNZIONESA_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\GRUPPIMEMBRI_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\GRUPPIMEMBRI_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\GRUPPIMEMBRI_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\GRUPPO_NOME_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\GRUPPO_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\GRUPPO_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\IDENTITA_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\IDENTITA_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\IDENTITA_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\IDENTITA_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\PIATTAFAPPCOMPARCH_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\PIATTAFAPPCOMPARCH_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\PIATTAFAPPCOMPARCH_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\PIATTAFAPPCOMPARCH_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\PIATTAFORMA_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\PIATTAFORMA_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\PIATTAFORMA_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\PIATTAFORMA_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\PIATTAFSERVTECNCOMPARCH_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\PIATTAFSERVTECNCOMPARCH_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\PIATTAFSERVTECNCOMPARCH_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\PIATTAFSERVTECNCOMPARCH_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\RECORDOFPROCESSINGACTIVITY_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\RECORDOFPROCESSINGACTIVITY_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\RECORDOFPROCESSINGACTIVITY_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\RESPONSABILEAPPLICATIVO_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\RESPONSABILEAPPLICATIVO_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\RESPONSABILEAPPLICATIVO_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ROPARIGHETESTO_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\ROPARIGHETESTO_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\RUOLIFUNZIONISA_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\RUOLIFUNZIONISA_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\RUOLIFUNZIONISA_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\RUOLOSA_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\RUOLOSA_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\RUOLOSA_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVER_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVER_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVER_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVER_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_NOME_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_N58.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_N59.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_N56.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_N57.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_N54.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_N55.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_N52.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_N53.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_N61.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_N51.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZIOTECNICO_N60.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIAMBIENTISDLC_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIAMBIENTISDLC_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIAMBIENTISDLC_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIAMBIENTISDLC_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIAPP_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIAPP_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIAPP_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIAPP_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICICOMPARCH_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICICOMPARCH_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICICOMPARCH_N51.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICICOMPARCH_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICICOMPARCH_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIENDPOINTS_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIENDPOINTS_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIENDPOINTS_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIENDPOINTS_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICISERVTEC_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICISERVTEC_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICISERVTEC_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICISERVTEC_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIVERSIONI_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIVERSIONI_UNQ.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SERVIZITECNICIVERSIONI_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TABELLADBDATIPERSONALI_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TABELLADBDATIPERSONALI_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TABELLADBDATIPERSONALI_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SHARE_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SHARE_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\SHARE_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TECHDATABASE_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TECHDATABASE_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TECHDATABASE_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TECNOLOGIASW_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TECNOLOGIASW_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TECNOLOGIASW_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TECNOLOGIASWSERVIZI_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TECNOLOGIASWSERVIZI_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TECNOLOGIASWSERVIZI_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOAPPLICAZIONE_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOAPPLICAZIONE_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOAPPLICAZIONE_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOASSET_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOASSET_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOASSET_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOASSET_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOAUTENTICAZIONE_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOAUTENTICAZIONE_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOAUTENTICAZIONE_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOAUTORIZZAZIONE_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOAUTORIZZAZIONE_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOAUTORIZZAZIONE_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOCOMPONENTE_UNQ3.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOCOMPONENTE_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOCOMPONENTE_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOCOMPONENTE_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOCOMPONENTESERVIZI_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOCOMPONENTESERVIZI_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOCOMPONENTESERVIZI_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPODATABASE_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPODATABASE_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPODATABASE_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOENDPOINT_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOENDPOINTSERVIZI_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOENDPOINTSERVIZI_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOGRUPPO_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOGRUPPO_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOGRUPPO_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOFRUIZIONE_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOFRUIZIONE_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOFRUIZIONE_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOIDENTITA_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOIDENTITA_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOIDENTITA_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOINDICE3_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOINDICE3_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOINDICE3_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOINFRASTRUTTURAASUPP_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOINFRASTRUTTURAASUPP_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOINFRASTRUTTURAASUPP_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOINSTALLAZIONESUDISP_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOINSTALLAZIONESUDISP_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOINSTALLAZIONESUDISP_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOPROCESSINGACTIVITY_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOPROCESSINGACTIVITY_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOPROCESSINGACTIVITY_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSCM_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSCM_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSCM_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSDL1_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSDL1_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSDL1_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSDL2_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSDL2_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSDL2_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSDL3_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSDL3_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSDL3_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSERVIZIOTECNICO_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSERVIZIOTECNICO_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSERVIZIOTECNICO_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSICUREZZA_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSICUREZZA_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSICUREZZA_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSICUREZZA_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSICUREZZA_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSSO_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSSO_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOSSO_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOUTENTE_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOUTENTE_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOUTENTE_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOUTENTETECNICO_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOUTENTETECNICO_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOUTENTETECNICO_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOUTENTETECNICO_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOUTENZADIDATABASE_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOUTENZADIDATABASE_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\TIPOUTENZADIDATABASE_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\UNITAORGANIZZATIVA_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\UNITAORGANIZZATIVA_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\UNITAORGANIZZATIVA_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\UTENTE_UNQ2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\UTENTE_UNQ1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\UTENTE_N49.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\UTENTE_N51.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\UTENTE_N50.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\INDEXES\UTENTE_PK.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\ADSAPPLICAZIONI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\ADSSERVIZITECNICI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\AMBIENTESDLC.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\AMMINISTRATOREDISISTEMA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\APPLICAZIONE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\APPLICAZIONESA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\APPLICAZIONIAMBIENTISDLC.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\APPLICAZIONICOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\APPLICAZIONIDATIPERSONALI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\APPLICAZIONISERVIZITECNICI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\APPLICAZIONIVERSIONI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\AREAAPPLICATIVA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\ATTIVITA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\ATTIVITAUTENTI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\CATEGORIADATI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\CATEGORIAINTERESSATI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\CONTESTOAPPLICATIVO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\CONTRATTO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\CONTRATTOAPP.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\DATABASE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\DATABASEAPPCOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\DATABASESERVTECNCOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\DATODADB.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\DATODADBRIGHETESTO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\FUNZIONESA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\GRUPPIMEMBRI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\GRUPPO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\IDENTITA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\PIATTAFAPPCOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\PIATTAFORMA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\PIATTAFSERVTECNCOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\RECORDOFPROCESSINGACTIVITY.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\RESPONSABILEAPPLICATIVO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\ROPARIGHETESTO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\RUOLIFUNZIONISA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\RUOLOSA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\SERVER.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\SERVIZIOTECNICO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\SERVIZITECNICIAMBIENTISDLC.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\SERVIZITECNICIAPP.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\SERVIZITECNICICOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\SERVIZITECNICIENDPOINTS.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\SERVIZITECNICISERVTEC.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\SERVIZITECNICIVERSIONI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TABELLADBDATIPERSONALI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\SHARE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TECHDATABASE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TECNOLOGIASW.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TECNOLOGIASWSERVIZI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOAPPLICAZIONE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOASSET.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOAUTENTICAZIONE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOAUTORIZZAZIONE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOCOMPONENTE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOCOMPONENTESERVIZI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPODATABASE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOENDPOINT.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOGRUPPO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOFRUIZIONE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOIDENTITA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOINDICE3.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOINFRASTRUTTURAASUPP.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOINSTALLAZIONESUDISP.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOPROCESSINGACTIVITY.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOSCM.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOSDL1.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOSDL2.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOSDL3.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOSERVIZIOTECNICO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOSICUREZZA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOSSO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOUTENTE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOUTENTETECNICO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\TIPOUTENZADIDATABASE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\UNITAORGANIZZATIVA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\CONSTRAINTS\UTENTE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\ADSAPPLICAZIONI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\ADSSERVIZITECNICI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\AMMINISTRATOREDISISTEMA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\APPLICAZIONE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\APPLICAZIONESA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\APPLICAZIONIAMBIENTISDLC.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\APPLICAZIONICOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\APPLICAZIONIDATIPERSONALI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\APPLICAZIONISERVIZITECNICI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\APPLICAZIONIVERSIONI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\ATTIVITA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\ATTIVITAUTENTI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\CONTRATTOAPP.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\DATABASE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\DATABASEAPPCOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\DATABASESERVTECNCOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\DATODADBRIGHETESTO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\FUNZIONESA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\GRUPPIMEMBRI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\GRUPPO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\IDENTITA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\PIATTAFAPPCOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\PIATTAFORMA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\PIATTAFSERVTECNCOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\RECORDOFPROCESSINGACTIVITY.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\ROPARIGHETESTO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\RUOLIFUNZIONISA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\RUOLOSA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\SERVER.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\SERVIZIOTECNICO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\SERVIZITECNICIAMBIENTISDLC.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\SERVIZITECNICIAPP.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\SERVIZITECNICICOMPARCH.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\SERVIZITECNICIENDPOINTS.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\SERVIZITECNICISERVTEC.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\SERVIZITECNICIVERSIONI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\TABELLADBDATIPERSONALI.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\SHARE.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\TIPOASSET.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\TIPOSICUREZZA.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\TIPOUTENTETECNICO.sql
@C:\Users\008568\OneDrive - RAI Radio Televisione Italiana Spa\Documenti\itg\t\REF_CONSTRAINTS\UTENTE.sql
