--------------------------------------------------------
--  Ref Constraints for Table ADSAPPLICAZIONI
--------------------------------------------------------

  ALTER TABLE "ADSAPPLICAZIONI" ADD CONSTRAINT "ADSAPPLICAZIONI_FK1" FOREIGN KEY ("AMMINISTRATOREDISISTEMA_AMMINISTRATOREDISISTEMA_ID_OID") REFERENCES "AMMINISTRATOREDISISTEMA" ("AMMINISTRATOREDISISTEMA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "ADSAPPLICAZIONI" ADD CONSTRAINT "ADSAPPLICAZIONI_FK2" FOREIGN KEY ("APPLICAZIONE_APPLICAZIONE_ID_OID") REFERENCES "APPLICAZIONE" ("APPLICAZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
