--------------------------------------------------------
--  Ref Constraints for Table ADSSERVIZITECNICI
--------------------------------------------------------

  ALTER TABLE "ADSSERVIZITECNICI" ADD CONSTRAINT "ADSSERVIZITECNICI_FK1" FOREIGN KEY ("AMMINISTRATOREDISISTEMA_AMMINISTRATOREDISISTEMA_ID_OID") REFERENCES "AMMINISTRATOREDISISTEMA" ("AMMINISTRATOREDISISTEMA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "ADSSERVIZITECNICI" ADD CONSTRAINT "ADSSERVIZITECNICI_FK2" FOREIGN KEY ("SERVIZIOTECNICO_SERVIZIO_ID_OID") REFERENCES "SERVIZIOTECNICO" ("SERVIZIO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
