--------------------------------------------------------
--  Ref Constraints for Table AMMINISTRATOREDISISTEMA
--------------------------------------------------------

  ALTER TABLE "AMMINISTRATOREDISISTEMA" ADD CONSTRAINT "AMMINISTRATOREDISISTEMA_FK1" FOREIGN KEY ("RESPONSABILEAPPLICATIVO_RESPONSABILEAPPLICATIVO_ID_OID") REFERENCES "RESPONSABILEAPPLICATIVO" ("RESPONSABILEAPPLICATIVO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
