--------------------------------------------------------
--  Ref Constraints for Table APPLICAZIONIAMBIENTISDLC
--------------------------------------------------------

  ALTER TABLE "APPLICAZIONIAMBIENTISDLC" ADD CONSTRAINT "APPLICAZIONIAMBIENTISDLC_FK1" FOREIGN KEY ("AMBIENTESDLC_AMBIENTESDLC_ID_OID") REFERENCES "AMBIENTESDLC" ("AMBIENTESDLC_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONIAMBIENTISDLC" ADD CONSTRAINT "APPLICAZIONIAMBIENTISDLC_FK2" FOREIGN KEY ("APPLICAZIONE_APPLICAZIONE_ID_OID") REFERENCES "APPLICAZIONE" ("APPLICAZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
