--------------------------------------------------------
--  Ref Constraints for Table APPLICAZIONIVERSIONI
--------------------------------------------------------

  ALTER TABLE "APPLICAZIONIVERSIONI" ADD CONSTRAINT "APPLICAZIONIVERSIONI_FK1" FOREIGN KEY ("APPLICAZIONE_APPLICAZIONE_ID_OID") REFERENCES "APPLICAZIONE" ("APPLICAZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
