--------------------------------------------------------
--  Ref Constraints for Table APPLICAZIONIDATIPERSONALI
--------------------------------------------------------

  ALTER TABLE "APPLICAZIONIDATIPERSONALI" ADD CONSTRAINT "APPLICAZIONIDATIPERSONALI_FK1" FOREIGN KEY ("APPLICAZIONE_APPLICAZIONE_ID_OID") REFERENCES "APPLICAZIONE" ("APPLICAZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONIDATIPERSONALI" ADD CONSTRAINT "APPLICAZIONIDATIPERSONALI_FK2" FOREIGN KEY ("CATEGORIADATI_CATEGORIADATI_ID_OID") REFERENCES "CATEGORIADATI" ("CATEGORIADATI_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONIDATIPERSONALI" ADD CONSTRAINT "APPLICAZIONIDATIPERSONALI_FK3" FOREIGN KEY ("CATEGORIAINTERESSATI_CATEGORIAINTERESSATI_ID_OID") REFERENCES "CATEGORIAINTERESSATI" ("CATEGORIAINTERESSATI_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
