--------------------------------------------------------
--  Ref Constraints for Table APPLICAZIONISERVIZITECNICI
--------------------------------------------------------

  ALTER TABLE "APPLICAZIONISERVIZITECNICI" ADD CONSTRAINT "APPLICAZIONISERVIZITECNICI_FK1" FOREIGN KEY ("APPLICAZIONE_APPLICAZIONE_ID_OID") REFERENCES "APPLICAZIONE" ("APPLICAZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONISERVIZITECNICI" ADD CONSTRAINT "APPLICAZIONISERVIZITECNICI_FK2" FOREIGN KEY ("SERVIZIOTECNICO_SERVIZIO_ID_OID") REFERENCES "SERVIZIOTECNICO" ("SERVIZIO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
