--------------------------------------------------------
--  Ref Constraints for Table APPLICAZIONICOMPARCH
--------------------------------------------------------

  ALTER TABLE "APPLICAZIONICOMPARCH" ADD CONSTRAINT "APPLICAZIONICOMPARCH_FK1" FOREIGN KEY ("APPLICAZIONE_APPLICAZIONE_ID_OID") REFERENCES "APPLICAZIONE" ("APPLICAZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONICOMPARCH" ADD CONSTRAINT "APPLICAZIONICOMPARCH_FK2" FOREIGN KEY ("TECNOLOGIASW_TECNOLOGIASW_ID_OID") REFERENCES "TECNOLOGIASW" ("TECNOLOGIASW_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONICOMPARCH" ADD CONSTRAINT "APPLICAZIONICOMPARCH_FK3" FOREIGN KEY ("TIPOCOMPONENTE_TIPOCOMPONENTE_ID_OID") REFERENCES "TIPOCOMPONENTE" ("TIPOCOMPONENTE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
