--------------------------------------------------------
--  Ref Constraints for Table APPLICAZIONE
--------------------------------------------------------

  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK1" FOREIGN KEY ("AREAAPPLICATIVA_AREAAPPLICATIVA_ID_OID") REFERENCES "AREAAPPLICATIVA" ("AREAAPPLICATIVA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK2" FOREIGN KEY ("CODICESICUREZZAAPPLICATIVA_APPLICAZIONESA_ID_OID") REFERENCES "APPLICAZIONESA" ("APPLICAZIONESA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK3" FOREIGN KEY ("CONTESTOAPPLICATIVO_CONTESTOAPPLICATIVO_ID_OID") REFERENCES "CONTESTOAPPLICATIVO" ("CONTESTOAPPLICATIVO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK4" FOREIGN KEY ("DATABASE_TIPODATABASE_ID_OID") REFERENCES "TIPODATABASE" ("TIPODATABASE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK4B" FOREIGN KEY ("INSTALLAZIONESUDISPOSITIVO_TIPOINSTALLAZIONESUDISP_ID_OID") REFERENCES "TIPOINSTALLAZIONESUDISP" ("TIPOINSTALLAZIONESUDISP_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK4C" FOREIGN KEY ("RESPONSABILEAPPLICATIVO_RESPONSABILEAPPLICATIVO_ID_OID") REFERENCES "RESPONSABILEAPPLICATIVO" ("RESPONSABILEAPPLICATIVO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK4D" FOREIGN KEY ("RISCHIOFINANZIARIO_TIPOINDICE3_ID_OID") REFERENCES "TIPOINDICE3" ("TIPOINDICE3_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK4E" FOREIGN KEY ("RISCHIOLEGALE_TIPOINDICE3_ID_OID") REFERENCES "TIPOINDICE3" ("TIPOINDICE3_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK4F" FOREIGN KEY ("RISCHIOREPUTAZIONALE_TIPOINDICE3_ID_OID") REFERENCES "TIPOINDICE3" ("TIPOINDICE3_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK5" FOREIGN KEY ("IMPATTOCONTINUITAOPERATIVA_TIPOINDICE3_ID_OID") REFERENCES "TIPOINDICE3" ("TIPOINDICE3_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK50" FOREIGN KEY ("SERVICEDESKL1_TIPOSDL1_ID_OID") REFERENCES "TIPOSDL1" ("TIPOSDL1_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK51" FOREIGN KEY ("SERVICEDESKL2_TIPOSDL2_ID_OID") REFERENCES "TIPOSDL2" ("TIPOSDL2_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK52" FOREIGN KEY ("SERVICEDESKL3_TIPOSDL3_ID_OID") REFERENCES "TIPOSDL3" ("TIPOSDL3_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK53" FOREIGN KEY ("SSO_TIPOSSO_ID_OID") REFERENCES "TIPOSSO" ("TIPOSSO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK54" FOREIGN KEY ("TIPOAPPLICAZIONE_TIPOAPPLICAZIONE_ID_OID") REFERENCES "TIPOAPPLICAZIONE" ("TIPOAPPLICAZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK55" FOREIGN KEY ("TIPODIAUTENTICAZIONE_TIPOAUTENTICAZIONE_ID_OID") REFERENCES "TIPOAUTENTICAZIONE" ("TIPOAUTENTICAZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK56" FOREIGN KEY ("TIPODIAUTORIZZAZIONE_TIPOAUTORIZZAZIONE_ID_OID") REFERENCES "TIPOAUTORIZZAZIONE" ("TIPOAUTORIZZAZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK57" FOREIGN KEY ("TIPOFRUIZIONE_TIPOFRUIZIONE_ID_OID") REFERENCES "TIPOFRUIZIONE" ("TIPOFRUIZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK58" FOREIGN KEY ("TIPOREPOSITORY_TIPOSCM_ID_OID") REFERENCES "TIPOSCM" ("TIPOSCM_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK59" FOREIGN KEY ("TIPOSICUREZZA_TIPOSICUREZZA_ID_OID") REFERENCES "TIPOSICUREZZA" ("TIPOSICUREZZA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK5A" FOREIGN KEY ("UTENZADIDATABASE_TIPOUTENZADIDATABASE_ID_OID") REFERENCES "TIPOUTENZADIDATABASE" ("TIPOUTENZADIDATABASE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK6" FOREIGN KEY ("IMPATTOPERDITADATI_TIPOINDICE3_ID_OID") REFERENCES "TIPOINDICE3" ("TIPOINDICE3_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK7" FOREIGN KEY ("INDICEDICRITICITA_TIPOINDICE3_ID_OID") REFERENCES "TIPOINDICE3" ("TIPOINDICE3_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK8" FOREIGN KEY ("INDICEDIMOVIMENTAZIONE_TIPOINDICE3_ID_OID") REFERENCES "TIPOINDICE3" ("TIPOINDICE3_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_FK9" FOREIGN KEY ("INFRASTRUTTURAASUPPORTO_TIPOINFRASTRUTTURAASUPPORTO_ID_OID") REFERENCES "TIPOINFRASTRUTTURAASUPP" ("TIPOINFRASTRUTTURAASUPPORTO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
