--------------------------------------------------------
--  Ref Constraints for Table ATTIVITAUTENTI
--------------------------------------------------------

  ALTER TABLE "ATTIVITAUTENTI" ADD CONSTRAINT "ATTIVITAUTENTI_FK1" FOREIGN KEY ("ATTIVITA_ATTIVITA_ID_OID") REFERENCES "ATTIVITA" ("ATTIVITA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "ATTIVITAUTENTI" ADD CONSTRAINT "ATTIVITAUTENTI_FK2" FOREIGN KEY ("UTENTE_UTENTE_ID_OID") REFERENCES "UTENTE" ("UTENTE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
