--------------------------------------------------------
--  Ref Constraints for Table ATTIVITA
--------------------------------------------------------

  ALTER TABLE "ATTIVITA" ADD CONSTRAINT "ATTIVITA_FK1" FOREIGN KEY ("ATTIVITAUTENTISERVICE_ATTIVITA_UTENTE_ID_OID") REFERENCES "ATTIVITAUTENTI" ("ATTIVITA_UTENTE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "ATTIVITA" ADD CONSTRAINT "ATTIVITA_FK2" FOREIGN KEY ("CONTRATTO_CONTRATTO_ID_OID") REFERENCES "CONTRATTO" ("CONTRATTO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "ATTIVITA" ADD CONSTRAINT "ATTIVITA_FK3" FOREIGN KEY ("TIPOUTENTE_TIPOUTENTETECNICO_ID_OID") REFERENCES "TIPOUTENTETECNICO" ("TIPOUTENTETECNICO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
