--------------------------------------------------------
--  Ref Constraints for Table CONTRATTOAPP
--------------------------------------------------------

  ALTER TABLE "CONTRATTOAPP" ADD CONSTRAINT "CONTRATTOAPP_FK1" FOREIGN KEY ("APPLICAZIONE_APPLICAZIONE_ID_OID") REFERENCES "APPLICAZIONE" ("APPLICAZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "CONTRATTOAPP" ADD CONSTRAINT "CONTRATTOAPP_FK2" FOREIGN KEY ("CONTRATTO_CONTRATTO_ID_OID") REFERENCES "CONTRATTO" ("CONTRATTO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
