--------------------------------------------------------
--  Ref Constraints for Table DATABASEAPPCOMPARCH
--------------------------------------------------------

  ALTER TABLE "DATABASEAPPCOMPARCH" ADD CONSTRAINT "DATABASEAPPCOMPARCH_FK1" FOREIGN KEY ("APPLICAZIONECOMPONENTEARCHITETTURA_APPLICAZIONE_COMPARCH_ID_OID") REFERENCES "APPLICAZIONICOMPARCH" ("APPLICAZIONE_COMPARCH_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "DATABASEAPPCOMPARCH" ADD CONSTRAINT "DATABASEAPPCOMPARCH_FK2" FOREIGN KEY ("DATABASE_DATABASE_ID_OID") REFERENCES "DATABASE" ("DATABASE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
