--------------------------------------------------------
--  Ref Constraints for Table DATABASESERVTECNCOMPARCH
--------------------------------------------------------

  ALTER TABLE "DATABASESERVTECNCOMPARCH" ADD CONSTRAINT "DATABASESERVTECNCOMPARCH_FK1" FOREIGN KEY ("DATABASE_DATABASE_ID_OID") REFERENCES "DATABASE" ("DATABASE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "DATABASESERVTECNCOMPARCH" ADD CONSTRAINT "DATABASESERVTECNCOMPARCH_FK2" FOREIGN KEY ("SERVIZIOTECNICOCOMPONENTEARCHITETTURA_SERVIZIOTECNICO_COMPONENTE_ID_OID") REFERENCES "SERVIZITECNICICOMPARCH" ("SERVIZIOTECNICO_COMPONENTE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
