--------------------------------------------------------
--  Ref Constraints for Table DATABASE
--------------------------------------------------------

  ALTER TABLE "DATABASE" ADD CONSTRAINT "DATABASE_FK1" FOREIGN KEY ("AMBIENTESDLC_AMBIENTESDLC_ID_OID") REFERENCES "AMBIENTESDLC" ("AMBIENTESDLC_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "DATABASE" ADD CONSTRAINT "DATABASE_FK2" FOREIGN KEY ("SERVER_SERVER_ID_OID") REFERENCES "SERVER" ("SERVER_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "DATABASE" ADD CONSTRAINT "DATABASE_FK3" FOREIGN KEY ("TECHDATABASE_TECHDATABASE_ID_OID") REFERENCES "TECHDATABASE" ("TECHDATABASE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
