--------------------------------------------------------
--  Ref Constraints for Table FUNZIONESA
--------------------------------------------------------

  ALTER TABLE "FUNZIONESA" ADD CONSTRAINT "FUNZIONESA_FK1" FOREIGN KEY ("APPLICAZIONESICUREZZAAPPLICATIVA_APPLICAZIONESA_ID_OID") REFERENCES "APPLICAZIONESA" ("APPLICAZIONESA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "FUNZIONESA" ADD CONSTRAINT "FUNZIONESA_FK2" FOREIGN KEY ("FUNZIONESASUP_FUNZIONESA_ID_OID") REFERENCES "FUNZIONESA" ("FUNZIONESA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
