--------------------------------------------------------
--  Ref Constraints for Table GRUPPIMEMBRI
--------------------------------------------------------

  ALTER TABLE "GRUPPIMEMBRI" ADD CONSTRAINT "GRUPPIMEMBRI_FK1" FOREIGN KEY ("GRUPPO_GRUPPO_ID_OID") REFERENCES "GRUPPO" ("GRUPPO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "GRUPPIMEMBRI" ADD CONSTRAINT "GRUPPIMEMBRI_FK2" FOREIGN KEY ("UTENTE_UTENTE_ID_OID") REFERENCES "UTENTE" ("UTENTE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
