--------------------------------------------------------
--  Ref Constraints for Table IDENTITA
--------------------------------------------------------

  ALTER TABLE "IDENTITA" ADD CONSTRAINT "IDENTITA_FK1" FOREIGN KEY ("TIPOIDENTITA_TIPOIDENTITA_ID_OID") REFERENCES "TIPOIDENTITA" ("TIPOIDENTITA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "IDENTITA" ADD CONSTRAINT "IDENTITA_FK2" FOREIGN KEY ("UNITAORGANIZZATIVA_UNITAORGANIZZATIVA_ID_OID") REFERENCES "UNITAORGANIZZATIVA" ("UNITAORGANIZZATIVA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
