--------------------------------------------------------
--  Ref Constraints for Table PIATTAFSERVTECNCOMPARCH
--------------------------------------------------------

  ALTER TABLE "PIATTAFSERVTECNCOMPARCH" ADD CONSTRAINT "PIATTAFSERVTECNCOMPARCH_FK1" FOREIGN KEY ("PIATTAFORMA_PIATTAFORMA_ID_OID") REFERENCES "PIATTAFORMA" ("PIATTAFORMA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "PIATTAFSERVTECNCOMPARCH" ADD CONSTRAINT "PIATTAFSERVTECNCOMPARCH_FK2" FOREIGN KEY ("SERVIZIOTECNICOCOMPONENTEARCHITETTURA_SERVIZIOTECNICO_COMPONENTE_ID_OID") REFERENCES "SERVIZITECNICICOMPARCH" ("SERVIZIOTECNICO_COMPONENTE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
