--------------------------------------------------------
--  Ref Constraints for Table PIATTAFAPPCOMPARCH
--------------------------------------------------------

  ALTER TABLE "PIATTAFAPPCOMPARCH" ADD CONSTRAINT "PIATTAFAPPCOMPARCH_FK1" FOREIGN KEY ("APPLICAZIONECOMPONENTEARCHITETTURA_APPLICAZIONE_COMPARCH_ID_OID") REFERENCES "APPLICAZIONICOMPARCH" ("APPLICAZIONE_COMPARCH_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "PIATTAFAPPCOMPARCH" ADD CONSTRAINT "PIATTAFAPPCOMPARCH_FK2" FOREIGN KEY ("PIATTAFORMA_PIATTAFORMA_ID_OID") REFERENCES "PIATTAFORMA" ("PIATTAFORMA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
