--------------------------------------------------------
--  Ref Constraints for Table PIATTAFORMA
--------------------------------------------------------

  ALTER TABLE "PIATTAFORMA" ADD CONSTRAINT "PIATTAFORMA_FK1" FOREIGN KEY ("AMBIENTESDLC_AMBIENTESDLC_ID_OID") REFERENCES "AMBIENTESDLC" ("AMBIENTESDLC_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "PIATTAFORMA" ADD CONSTRAINT "PIATTAFORMA_FK2" FOREIGN KEY ("INFRASTRUTTURAASUPPORTO_TIPOINFRASTRUTTURAASUPPORTO_ID_OID") REFERENCES "TIPOINFRASTRUTTURAASUPP" ("TIPOINFRASTRUTTURAASUPPORTO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
