--------------------------------------------------------
--  Ref Constraints for Table RECORDOFPROCESSINGACTIVITY
--------------------------------------------------------

  ALTER TABLE "RECORDOFPROCESSINGACTIVITY" ADD CONSTRAINT "RECORDOFPROCESSINGACTIVITY_FK1" FOREIGN KEY ("ROPARIGATESTOSERVICE_ROPA_RIGATESTO_ID_OID") REFERENCES "ROPARIGHETESTO" ("ROPA_RIGATESTO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "RECORDOFPROCESSINGACTIVITY" ADD CONSTRAINT "RECORDOFPROCESSINGACTIVITY_FK2" FOREIGN KEY ("TIPOROPA_TIPOPROCESSINGACTIVITY_ID_OID") REFERENCES "TIPOPROCESSINGACTIVITY" ("TIPOPROCESSINGACTIVITY_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
