--------------------------------------------------------
--  Ref Constraints for Table RUOLIFUNZIONISA
--------------------------------------------------------

  ALTER TABLE "RUOLIFUNZIONISA" ADD CONSTRAINT "RUOLIFUNZIONISA_FK1" FOREIGN KEY ("RUOLOSA_ID") REFERENCES "RUOLOSA" ("RUOLOSA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "RUOLIFUNZIONISA" ADD CONSTRAINT "RUOLIFUNZIONISA_FK2" FOREIGN KEY ("FUNZIONESA_ID") REFERENCES "FUNZIONESA" ("FUNZIONESA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
