--------------------------------------------------------
--  Ref Constraints for Table SERVIZITECNICIENDPOINTS
--------------------------------------------------------

  ALTER TABLE "SERVIZITECNICIENDPOINTS" ADD CONSTRAINT "SERVIZITECNICIENDPOINTS_FK1" FOREIGN KEY ("SERVIZIOTECNICO_SERVIZIO_ID_OID") REFERENCES "SERVIZIOTECNICO" ("SERVIZIO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZITECNICIENDPOINTS" ADD CONSTRAINT "SERVIZITECNICIENDPOINTS_FK2" FOREIGN KEY ("TIPOENDPOINT_TIPOENDPOINTSERVIZI_ID_OID") REFERENCES "TIPOENDPOINT" ("TIPOENDPOINTSERVIZI_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
