--------------------------------------------------------
--  Ref Constraints for Table SERVIZIOTECNICO
--------------------------------------------------------

  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_FK1" FOREIGN KEY ("AREAAPPLICATIVA_AREAAPPLICATIVA_ID_OID") REFERENCES "AREAAPPLICATIVA" ("AREAAPPLICATIVA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_FK2" FOREIGN KEY ("CONTESTOAPPLICATIVO_CONTESTOAPPLICATIVO_ID_OID") REFERENCES "CONTESTOAPPLICATIVO" ("CONTESTOAPPLICATIVO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_FK3" FOREIGN KEY ("DATABASE_TIPODATABASE_ID_OID") REFERENCES "TIPODATABASE" ("TIPODATABASE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_FK4" FOREIGN KEY ("INDICEDICRITICITA_TIPOINDICE3_ID_OID") REFERENCES "TIPOINDICE3" ("TIPOINDICE3_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_FK4B" FOREIGN KEY ("TIPOREPOSITORY_TIPOSCM_ID_OID") REFERENCES "TIPOSCM" ("TIPOSCM_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_FK4C" FOREIGN KEY ("TIPOSERVIZIOTECNICO_TIPOSERVIZIOTECNICO_ID_OID") REFERENCES "TIPOSERVIZIOTECNICO" ("TIPOSERVIZIOTECNICO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_FK4D" FOREIGN KEY ("TIPOSICUREZZA_TIPOSICUREZZA_ID_OID") REFERENCES "TIPOSICUREZZA" ("TIPOSICUREZZA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_FK4E" FOREIGN KEY ("UTENZADIDATABASE_TIPOUTENZADIDATABASE_ID_OID") REFERENCES "TIPOUTENZADIDATABASE" ("TIPOUTENZADIDATABASE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_FK5" FOREIGN KEY ("INDICEDIMOVIMENTAZIONE_TIPOINDICE3_ID_OID") REFERENCES "TIPOINDICE3" ("TIPOINDICE3_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_FK6" FOREIGN KEY ("RESPONSABILEAPPLICATIVO_RESPONSABILEAPPLICATIVO_ID_OID") REFERENCES "RESPONSABILEAPPLICATIVO" ("RESPONSABILEAPPLICATIVO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_FK7" FOREIGN KEY ("SSO_TIPOSSO_ID_OID") REFERENCES "TIPOSSO" ("TIPOSSO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_FK8" FOREIGN KEY ("TIPODIAUTENTICAZIONE_TIPOAUTENTICAZIONE_ID_OID") REFERENCES "TIPOAUTENTICAZIONE" ("TIPOAUTENTICAZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_FK9" FOREIGN KEY ("TIPODIAUTORIZZAZIONE_TIPOAUTORIZZAZIONE_ID_OID") REFERENCES "TIPOAUTORIZZAZIONE" ("TIPOAUTORIZZAZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
