--------------------------------------------------------
--  Ref Constraints for Table SERVIZITECNICIVERSIONI
--------------------------------------------------------

  ALTER TABLE "SERVIZITECNICIVERSIONI" ADD CONSTRAINT "SERVIZITECNICIVERSIONI_FK1" FOREIGN KEY ("SERVIZIOTECNICO_SERVIZIO_ID_OID") REFERENCES "SERVIZIOTECNICO" ("SERVIZIO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
