--------------------------------------------------------
--  Ref Constraints for Table SERVIZITECNICIAPP
--------------------------------------------------------

  ALTER TABLE "SERVIZITECNICIAPP" ADD CONSTRAINT "SERVIZITECNICIAPP_FK1" FOREIGN KEY ("APPLICAZIONE_APPLICAZIONE_ID_OID") REFERENCES "APPLICAZIONE" ("APPLICAZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZITECNICIAPP" ADD CONSTRAINT "SERVIZITECNICIAPP_FK2" FOREIGN KEY ("SERVIZIOTECNICO_SERVIZIO_ID_OID") REFERENCES "SERVIZIOTECNICO" ("SERVIZIO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
