--------------------------------------------------------
--  Ref Constraints for Table SERVIZITECNICIAMBIENTISDLC
--------------------------------------------------------

  ALTER TABLE "SERVIZITECNICIAMBIENTISDLC" ADD CONSTRAINT "SERVIZITECNICIAMBIENTISDLC_FK1" FOREIGN KEY ("AMBIENTESDLC_AMBIENTESDLC_ID_OID") REFERENCES "AMBIENTESDLC" ("AMBIENTESDLC_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZITECNICIAMBIENTISDLC" ADD CONSTRAINT "SERVIZITECNICIAMBIENTISDLC_FK2" FOREIGN KEY ("SERVIZIOTECNICO_SERVIZIO_ID_OID") REFERENCES "SERVIZIOTECNICO" ("SERVIZIO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
