--------------------------------------------------------
--  Ref Constraints for Table SERVER
--------------------------------------------------------

  ALTER TABLE "SERVER" ADD CONSTRAINT "SERVER_FK1" FOREIGN KEY ("AMBIENTESDLC_AMBIENTESDLC_ID_OID") REFERENCES "AMBIENTESDLC" ("AMBIENTESDLC_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVER" ADD CONSTRAINT "SERVER_FK2" FOREIGN KEY ("INFRASTRUTTURAASUPPORTO_TIPOINFRASTRUTTURAASUPPORTO_ID_OID") REFERENCES "TIPOINFRASTRUTTURAASUPP" ("TIPOINFRASTRUTTURAASUPPORTO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
