--------------------------------------------------------
--  Ref Constraints for Table SERVIZITECNICISERVTEC
--------------------------------------------------------

  ALTER TABLE "SERVIZITECNICISERVTEC" ADD CONSTRAINT "SERVIZITECNICISERVTEC_FK1" FOREIGN KEY ("SERVIZIOTECNICO_SERVIZIO_ID_OID") REFERENCES "SERVIZIOTECNICO" ("SERVIZIO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZITECNICISERVTEC" ADD CONSTRAINT "SERVIZITECNICISERVTEC_FK2" FOREIGN KEY ("SERVIZIOTECNICOREF_SERVIZIO_ID_OID") REFERENCES "SERVIZIOTECNICO" ("SERVIZIO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
