--------------------------------------------------------
--  Ref Constraints for Table SERVIZITECNICICOMPARCH
--------------------------------------------------------

  ALTER TABLE "SERVIZITECNICICOMPARCH" ADD CONSTRAINT "SERVIZITECNICICOMPARCH_FK1" FOREIGN KEY ("SERVIZIOTECNICO_SERVIZIO_ID_OID") REFERENCES "SERVIZIOTECNICO" ("SERVIZIO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZITECNICICOMPARCH" ADD CONSTRAINT "SERVIZITECNICICOMPARCH_FK2" FOREIGN KEY ("TECNOLOGIASW_TECNOLOGIASWSERVIZI_ID_OID") REFERENCES "TECNOLOGIASWSERVIZI" ("TECNOLOGIASWSERVIZI_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SERVIZITECNICICOMPARCH" ADD CONSTRAINT "SERVIZITECNICICOMPARCH_FK3" FOREIGN KEY ("TIPOCOMPONENTE_TIPOCOMPONENTESERVIZI_ID_OID") REFERENCES "TIPOCOMPONENTESERVIZI" ("TIPOCOMPONENTESERVIZI_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
