--------------------------------------------------------
--  Ref Constraints for Table SHARE
--------------------------------------------------------

  ALTER TABLE "SHARE" ADD CONSTRAINT "SHARE_FK1" FOREIGN KEY ("GRUPPOGRANTEE_GRUPPO_ID_OID") REFERENCES "GRUPPO" ("GRUPPO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "SHARE" ADD CONSTRAINT "SHARE_FK2" FOREIGN KEY ("PROPIETARIO_UNITAORGANIZZATIVA_ID_OID") REFERENCES "UNITAORGANIZZATIVA" ("UNITAORGANIZZATIVA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
