--------------------------------------------------------
--  Ref Constraints for Table TABELLADBDATIPERSONALI
--------------------------------------------------------

  ALTER TABLE "TABELLADBDATIPERSONALI" ADD CONSTRAINT "TABELLADBDATIPERSONALI_FK1" FOREIGN KEY ("APPLICAZIONE_APPLICAZIONE_ID_OID") REFERENCES "APPLICAZIONE" ("APPLICAZIONE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
