--------------------------------------------------------
--  Ref Constraints for Table TIPOSICUREZZA
--------------------------------------------------------

  ALTER TABLE "TIPOSICUREZZA" ADD CONSTRAINT "TIPOSICUREZZA_FK1" FOREIGN KEY ("TIPOSSO_TIPOSSO_ID_OID") REFERENCES "TIPOSSO" ("TIPOSSO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "TIPOSICUREZZA" ADD CONSTRAINT "TIPOSICUREZZA_FK2" FOREIGN KEY ("TIPOUTENZADIDATABASE_TIPOUTENZADIDATABASE_ID_OID") REFERENCES "TIPOUTENZADIDATABASE" ("TIPOUTENZADIDATABASE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
