--------------------------------------------------------
--  Ref Constraints for Table UTENTE
--------------------------------------------------------

  ALTER TABLE "UTENTE" ADD CONSTRAINT "UTENTE_FK1" FOREIGN KEY ("IDENTITA_IDENTITA_ID_OID") REFERENCES "IDENTITA" ("IDENTITA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "UTENTE" ADD CONSTRAINT "UTENTE_FK2" FOREIGN KEY ("TIPOUTENTE_TIPOUTENTE_ID_OID") REFERENCES "TIPOUTENTE" ("TIPOUTENTE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
  ALTER TABLE "UTENTE" ADD CONSTRAINT "UTENTE_FK3" FOREIGN KEY ("TIPOUTENTETECNICO_TIPOUTENTETECNICO_ID_OID") REFERENCES "TIPOUTENTETECNICO" ("TIPOUTENTETECNICO_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
