--------------------------------------------------------
--  DDL for Index APPLICAZIONIDATIPERSONALI_UNQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPLICAZIONIDATIPERSONALI_UNQ" ON "APPLICAZIONIDATIPERSONALI" ("APPLICAZIONE_APPLICAZIONE_ID_OID", "CATEGORIADATI_CATEGORIADATI_ID_OID", "CATEGORIAINTERESSATI_CATEGORIAINTERESSATI_ID_OID", "NOME")
