--------------------------------------------------------
--  DDL for Index APPLICAZIONICOMPARCH_UNQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPLICAZIONICOMPARCH_UNQ" ON "APPLICAZIONICOMPARCH" ("APPLICAZIONE_APPLICAZIONE_ID_OID", "TIPOCOMPONENTE_TIPOCOMPONENTE_ID_OID", "TECNOLOGIASW_TECNOLOGIASW_ID_OID", "URIREPOSITORY", "NONPIF9INUSO")
