--------------------------------------------------------
--  DDL for Index DATABASESERVTECNCOMPARCH_UNQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATABASESERVTECNCOMPARCH_UNQ" ON "DATABASESERVTECNCOMPARCH" ("DATABASE_DATABASE_ID_OID", "SERVIZIOTECNICOCOMPONENTEARCHITETTURA_SERVIZIOTECNICO_COMPONENTE_ID_OID")
