--------------------------------------------------------
--  DDL for Index PIATTAFSERVTECNCOMPARCH_UNQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIATTAFSERVTECNCOMPARCH_UNQ" ON "PIATTAFSERVTECNCOMPARCH" ("PIATTAFORMA_PIATTAFORMA_ID_OID", "SERVIZIOTECNICOCOMPONENTEARCHITETTURA_SERVIZIOTECNICO_COMPONENTE_ID_OID")
