--------------------------------------------------------
--  DDL for Index SERVIZITECNICICOMPARCH_UNQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "SERVIZITECNICICOMPARCH_UNQ" ON "SERVIZITECNICICOMPARCH" ("SERVIZIOTECNICO_SERVIZIO_ID_OID", "TIPOCOMPONENTE_TIPOCOMPONENTESERVIZI_ID_OID", "TECNOLOGIASW_TECNOLOGIASWSERVIZI_ID_OID", "URIREPOSITORY", "NONPIF9INUSO")
