--------------------------------------------------------
--  DDL for Index SERVIZITECNICIENDPOINTS_UNQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "SERVIZITECNICIENDPOINTS_UNQ" ON "SERVIZITECNICIENDPOINTS" ("SERVIZIOTECNICO_SERVIZIO_ID_OID", "TIPOENDPOINT_TIPOENDPOINTSERVIZI_ID_OID", "ENDPOINT", "NONPIUINUSO")
