--------------------------------------------------------
--  Constraints for Table ADSAPPLICAZIONI
--------------------------------------------------------

  ALTER TABLE "ADSAPPLICAZIONI" ADD CONSTRAINT "ADSAPPLICAZIONI_PK" PRIMARY KEY ("ADS_APPLICAZIONE_ID") USING INDEX  ENABLE
  ALTER TABLE "ADSAPPLICAZIONI" ADD CONSTRAINT "ADSAPPLICAZIONI_UNQ" UNIQUE ("AMMINISTRATOREDISISTEMA_AMMINISTRATOREDISISTEMA_ID_OID", "APPLICAZIONE_APPLICAZIONE_ID_OID") USING INDEX  ENABLE
  ALTER TABLE "ADSAPPLICAZIONI" MODIFY ("ADS_APPLICAZIONE_ID" NOT NULL ENABLE)
  ALTER TABLE "ADSAPPLICAZIONI" MODIFY ("VERSION" NOT NULL ENABLE)
