--------------------------------------------------------
--  Constraints for Table ADSSERVIZITECNICI
--------------------------------------------------------

  ALTER TABLE "ADSSERVIZITECNICI" ADD CONSTRAINT "ADSSERVIZITECNICI_PK" PRIMARY KEY ("ADS_SERVIZIOTECNICO_ID") USING INDEX  ENABLE
  ALTER TABLE "ADSSERVIZITECNICI" ADD CONSTRAINT "ADSSERVIZITECNICI_UNQ" UNIQUE ("AMMINISTRATOREDISISTEMA_AMMINISTRATOREDISISTEMA_ID_OID", "SERVIZIOTECNICO_SERVIZIO_ID_OID") USING INDEX  ENABLE
  ALTER TABLE "ADSSERVIZITECNICI" MODIFY ("ADS_SERVIZIOTECNICO_ID" NOT NULL ENABLE)
  ALTER TABLE "ADSSERVIZITECNICI" MODIFY ("VERSION" NOT NULL ENABLE)
