--------------------------------------------------------
--  Constraints for Table AMBIENTESDLC
--------------------------------------------------------

  ALTER TABLE "AMBIENTESDLC" ADD CONSTRAINT "AMBIENTESDLC_PK" PRIMARY KEY ("AMBIENTESDLC_ID") USING INDEX  ENABLE
  ALTER TABLE "AMBIENTESDLC" ADD CONSTRAINT "AMBIENTESDLC_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "AMBIENTESDLC" ADD CONSTRAINT "AMBIENTESDLC_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
  ALTER TABLE "AMBIENTESDLC" MODIFY ("AMBIENTESDLC_ID" NOT NULL ENABLE)
  ALTER TABLE "AMBIENTESDLC" MODIFY ("AMBIENTESDLC" NOT NULL ENABLE)
  ALTER TABLE "AMBIENTESDLC" MODIFY ("PRODUZIONE" NOT NULL ENABLE)
  ALTER TABLE "AMBIENTESDLC" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "AMBIENTESDLC" ADD CHECK (AMBIENTESDLC IN (1,0)) ENABLE
  ALTER TABLE "AMBIENTESDLC" ADD CHECK (PRODUZIONE IN (1,0)) ENABLE
