--------------------------------------------------------
--  Constraints for Table AMMINISTRATOREDISISTEMA
--------------------------------------------------------

  ALTER TABLE "AMMINISTRATOREDISISTEMA" ADD CONSTRAINT "ADS_UNQ" UNIQUE ("RESPONSABILEAPPLICATIVO_RESPONSABILEAPPLICATIVO_ID_OID", "TIPOADSIT") USING INDEX  ENABLE
  ALTER TABLE "AMMINISTRATOREDISISTEMA" ADD CONSTRAINT "AMMINISTRATOREDISISTEMA_PK" PRIMARY KEY ("AMMINISTRATOREDISISTEMA_ID") USING INDEX  ENABLE
  ALTER TABLE "AMMINISTRATOREDISISTEMA" MODIFY ("AMMINISTRATOREDISISTEMA_ID" NOT NULL ENABLE)
  ALTER TABLE "AMMINISTRATOREDISISTEMA" MODIFY ("AMBITODEFINITOPUNTUALMENTE" NOT NULL ENABLE)
  ALTER TABLE "AMMINISTRATOREDISISTEMA" MODIFY ("ATTIVO" NOT NULL ENABLE)
  ALTER TABLE "AMMINISTRATOREDISISTEMA" MODIFY ("ELENCODETTAGLIATO" NOT NULL ENABLE)
  ALTER TABLE "AMMINISTRATOREDISISTEMA" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "AMMINISTRATOREDISISTEMA" ADD CHECK (AMBITODEFINITOPUNTUALMENTE IN (1,0)) ENABLE
  ALTER TABLE "AMMINISTRATOREDISISTEMA" ADD CHECK (ATTIVO IN (1,0)) ENABLE
  ALTER TABLE "AMMINISTRATOREDISISTEMA" ADD CHECK (ELENCODETTAGLIATO IN (1,0)) ENABLE
