--------------------------------------------------------
--  Constraints for Table APPLICAZIONE
--------------------------------------------------------

  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_NOME_UNQ" UNIQUE ("NOME") USING INDEX  ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "APPLICAZIONE_PK" PRIMARY KEY ("APPLICAZIONE_ID") USING INDEX  ENABLE
  ALTER TABLE "APPLICAZIONE" MODIFY ("APPLICAZIONE_ID" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONE" MODIFY ("ATTRIBUZIONELICENZE" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONE" MODIFY ("DASOTTOPORREASOFTWAREANALYTICS" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONE" MODIFY ("DISMESSA" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONE" MODIFY ("NOME" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONE" MODIFY ("NUMEROUTENTI" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONE" MODIFY ("SICUREZZADIDOMINIO" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONE" MODIFY ("UTILIZZATADALBUSINESS" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONE" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONE" ADD CHECK (ATTRIBUZIONELICENZE IN (1,0)) ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CHECK (DASOTTOPORREASOFTWAREANALYTICS IN (1,0)) ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CHECK (DISMESSA IN (1,0)) ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CHECK (SICUREZZADIDOMINIO IN (1,0)) ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CHECK (UTILIZZATADALBUSINESS IN (1,0)) ENABLE
  ALTER TABLE "APPLICAZIONE" ADD CONSTRAINT "UNIQUE_DESC_TEST" UNIQUE ("DESCRIZIONE") USING INDEX  ENABLE
