--------------------------------------------------------
--  Constraints for Table APPLICAZIONESA
--------------------------------------------------------

  ALTER TABLE "APPLICAZIONESA" ADD CONSTRAINT "APPLICASIONESA_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "APPLICAZIONESA" ADD CONSTRAINT "APPLICAZIONESA_PK" PRIMARY KEY ("APPLICAZIONESA_ID") USING INDEX  ENABLE
  ALTER TABLE "APPLICAZIONESA" MODIFY ("APPLICAZIONESA_ID" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONESA" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONESA" ADD CHECK (DELETED IN (1,0) OR DELETED IS NULL) ENABLE
