--------------------------------------------------------
--  Constraints for Table APPLICAZIONISERVIZITECNICI
--------------------------------------------------------

  ALTER TABLE "APPLICAZIONISERVIZITECNICI" ADD CONSTRAINT "APPLICAZIONISERVIZITECNICI_PK" PRIMARY KEY ("APPLICAZIONE_SERVIZIOTECNICO_ID") USING INDEX  ENABLE
  ALTER TABLE "APPLICAZIONISERVIZITECNICI" ADD CONSTRAINT "APPLICAZIONISERVIZITECNICI_UNQ" UNIQUE ("APPLICAZIONE_APPLICAZIONE_ID_OID", "SERVIZIOTECNICO_SERVIZIO_ID_OID", "NONPIF9INUSO") USING INDEX  ENABLE
  ALTER TABLE "APPLICAZIONISERVIZITECNICI" MODIFY ("APPLICAZIONE_SERVIZIOTECNICO_ID" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONISERVIZITECNICI" MODIFY ("APPLICAZIONE_APPLICAZIONE_ID_OID" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONISERVIZITECNICI" MODIFY ("NONPIF9INUSO" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONISERVIZITECNICI" MODIFY ("SERVIZIOTECNICO_SERVIZIO_ID_OID" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONISERVIZITECNICI" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONISERVIZITECNICI" ADD CHECK (NONPIF9INUSO IN (1,0)) ENABLE
