--------------------------------------------------------
--  Constraints for Table APPLICAZIONIVERSIONI
--------------------------------------------------------

  ALTER TABLE "APPLICAZIONIVERSIONI" ADD CONSTRAINT "APPLICAZIONIVERSIONI_PK" PRIMARY KEY ("APPLICAZIONE_VERSIONI_ID") USING INDEX  ENABLE
  ALTER TABLE "APPLICAZIONIVERSIONI" ADD CONSTRAINT "APPLICAZIONIVERSIONI_UNQ" UNIQUE ("APPLICAZIONE_APPLICAZIONE_ID_OID", "TAG") USING INDEX  ENABLE
  ALTER TABLE "APPLICAZIONIVERSIONI" MODIFY ("APPLICAZIONE_VERSIONI_ID" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIVERSIONI" MODIFY ("APPLICAZIONE_APPLICAZIONE_ID_OID" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIVERSIONI" MODIFY ("PRODUZIONE" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIVERSIONI" MODIFY ("TAG" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIVERSIONI" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIVERSIONI" ADD CHECK (PRODUZIONE IN (1,0)) ENABLE
