--------------------------------------------------------
--  Constraints for Table APPLICAZIONIAMBIENTISDLC
--------------------------------------------------------

  ALTER TABLE "APPLICAZIONIAMBIENTISDLC" ADD CONSTRAINT "APPLICAZIONIAMBIENTISDLC_PK" PRIMARY KEY ("APPLICAZIONE_AMBIENTE_ID") USING INDEX  ENABLE
  ALTER TABLE "APPLICAZIONIAMBIENTISDLC" ADD CONSTRAINT "APPLICAZIONIAMBIENTISDLC_UNQ" UNIQUE ("APPLICAZIONE_APPLICAZIONE_ID_OID", "AMBIENTESDLC_AMBIENTESDLC_ID_OID") USING INDEX  ENABLE
  ALTER TABLE "APPLICAZIONIAMBIENTISDLC" MODIFY ("APPLICAZIONE_AMBIENTE_ID" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIAMBIENTISDLC" MODIFY ("URIDILANCIO" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIAMBIENTISDLC" MODIFY ("AMBIENTEDISPONIBILE" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIAMBIENTISDLC" MODIFY ("AMBIENTEGESTITO" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIAMBIENTISDLC" MODIFY ("AMBIENTESDLC_AMBIENTESDLC_ID_OID" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIAMBIENTISDLC" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIAMBIENTISDLC" ADD CHECK (AMBIENTEDISPONIBILE IN (1,0)) ENABLE
  ALTER TABLE "APPLICAZIONIAMBIENTISDLC" ADD CHECK (AMBIENTEGESTITO IN (1,0)) ENABLE
