--------------------------------------------------------
--  Constraints for Table APPLICAZIONIDATIPERSONALI
--------------------------------------------------------

  ALTER TABLE "APPLICAZIONIDATIPERSONALI" ADD CONSTRAINT "APPLICAZIONIDATIPERSONALI_PK" PRIMARY KEY ("APPLICAZIONE_DATI_PERSONALI_ID") USING INDEX  ENABLE
  ALTER TABLE "APPLICAZIONIDATIPERSONALI" ADD CONSTRAINT "APPLICAZIONIDATIPERSONALI_UNQ" UNIQUE ("APPLICAZIONE_APPLICAZIONE_ID_OID", "CATEGORIADATI_CATEGORIADATI_ID_OID", "CATEGORIAINTERESSATI_CATEGORIAINTERESSATI_ID_OID", "NOME") USING INDEX  ENABLE
  ALTER TABLE "APPLICAZIONIDATIPERSONALI" MODIFY ("APPLICAZIONE_DATI_PERSONALI_ID" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIDATIPERSONALI" MODIFY ("CATEGORIADATI_CATEGORIADATI_ID_OID" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIDATIPERSONALI" MODIFY ("CATEGORIAINTERESSATI_CATEGORIAINTERESSATI_ID_OID" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIDATIPERSONALI" MODIFY ("DESCRIZIONE" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIDATIPERSONALI" MODIFY ("NOME" NOT NULL ENABLE)
  ALTER TABLE "APPLICAZIONIDATIPERSONALI" MODIFY ("VERSION" NOT NULL ENABLE)
