--------------------------------------------------------
--  Constraints for Table AREAAPPLICATIVA
--------------------------------------------------------

  ALTER TABLE "AREAAPPLICATIVA" ADD CONSTRAINT "AREAAPPLICATIVA_PK" PRIMARY KEY ("AREAAPPLICATIVA_ID") USING INDEX  ENABLE
  ALTER TABLE "AREAAPPLICATIVA" ADD CONSTRAINT "AREAAPPLICATIVA_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "AREAAPPLICATIVA" ADD CONSTRAINT "AREAAPPLICATIVA_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
  ALTER TABLE "AREAAPPLICATIVA" MODIFY ("AREAAPPLICATIVA_ID" NOT NULL ENABLE)
  ALTER TABLE "AREAAPPLICATIVA" MODIFY ("ENABLED" NOT NULL ENABLE)
  ALTER TABLE "AREAAPPLICATIVA" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "AREAAPPLICATIVA" ADD CHECK (ENABLED IN (1,0)) ENABLE
