--------------------------------------------------------
--  Constraints for Table ATTIVITAUTENTI
--------------------------------------------------------

  ALTER TABLE "ATTIVITAUTENTI" ADD CONSTRAINT "ATTIVITAUTENTI_PK" PRIMARY KEY ("ATTIVITA_UTENTE_ID") USING INDEX  ENABLE
  ALTER TABLE "ATTIVITAUTENTI" ADD CONSTRAINT "ATTIVITAUTENTI_UNQ" UNIQUE ("ATTIVITA_ATTIVITA_ID_OID", "UTENTE_UTENTE_ID_OID") USING INDEX  ENABLE
  ALTER TABLE "ATTIVITAUTENTI" MODIFY ("ATTIVITA_UTENTE_ID" NOT NULL ENABLE)
  ALTER TABLE "ATTIVITAUTENTI" MODIFY ("VERSION" NOT NULL ENABLE)
