--------------------------------------------------------
--  Constraints for Table ATTIVITA
--------------------------------------------------------

  ALTER TABLE "ATTIVITA" ADD CONSTRAINT "ATTIVITA_PK" PRIMARY KEY ("ATTIVITA_ID") USING INDEX  ENABLE
  ALTER TABLE "ATTIVITA" ADD CONSTRAINT "ATTIVITA_UNQ" UNIQUE ("CONTRATTO_CONTRATTO_ID_OID", "DESCRIZIONE") USING INDEX  ENABLE
  ALTER TABLE "ATTIVITA" MODIFY ("ATTIVITA_ID" NOT NULL ENABLE)
  ALTER TABLE "ATTIVITA" MODIFY ("VERSION" NOT NULL ENABLE)
