--------------------------------------------------------
--  Constraints for Table CATEGORIADATI
--------------------------------------------------------

  ALTER TABLE "CATEGORIADATI" ADD CONSTRAINT "CATEGORIADATI_PK" PRIMARY KEY ("CATEGORIADATI_ID") USING INDEX  ENABLE
  ALTER TABLE "CATEGORIADATI" ADD CONSTRAINT "CATEGORIADATI_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "CATEGORIADATI" ADD CONSTRAINT "CATEGORIADATI_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
  ALTER TABLE "CATEGORIADATI" MODIFY ("CATEGORIADATI_ID" NOT NULL ENABLE)
  ALTER TABLE "CATEGORIADATI" MODIFY ("DELETED" NOT NULL ENABLE)
  ALTER TABLE "CATEGORIADATI" MODIFY ("LOG" NOT NULL ENABLE)
  ALTER TABLE "CATEGORIADATI" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "CATEGORIADATI" ADD CHECK (DELETED IN (1,0)) ENABLE
  ALTER TABLE "CATEGORIADATI" ADD CHECK (LOG IN (1,0)) ENABLE
