--------------------------------------------------------
--  Constraints for Table CATEGORIAINTERESSATI
--------------------------------------------------------

  ALTER TABLE "CATEGORIAINTERESSATI" ADD CONSTRAINT "CATEGORIAINTERESSATI_PK" PRIMARY KEY ("CATEGORIAINTERESSATI_ID") USING INDEX  ENABLE
  ALTER TABLE "CATEGORIAINTERESSATI" ADD CONSTRAINT "CATEGORIAINTERESSATI_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "CATEGORIAINTERESSATI" ADD CONSTRAINT "CATEGORIAINTERESSATI_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
  ALTER TABLE "CATEGORIAINTERESSATI" MODIFY ("CATEGORIAINTERESSATI_ID" NOT NULL ENABLE)
  ALTER TABLE "CATEGORIAINTERESSATI" MODIFY ("VERSION" NOT NULL ENABLE)
