--------------------------------------------------------
--  Constraints for Table CONTRATTO
--------------------------------------------------------

  ALTER TABLE "CONTRATTO" ADD CONSTRAINT "CONTRATTO_PK" PRIMARY KEY ("CONTRATTO_ID") USING INDEX  ENABLE
  ALTER TABLE "CONTRATTO" ADD CONSTRAINT "CONTRATTO_UNQ" UNIQUE ("PROTOCOLLO") USING INDEX  ENABLE
  ALTER TABLE "CONTRATTO" MODIFY ("CONTRATTO_ID" NOT NULL ENABLE)
  ALTER TABLE "CONTRATTO" MODIFY ("VERSION" NOT NULL ENABLE)
