--------------------------------------------------------
--  Constraints for Table CONTESTOAPPLICATIVO
--------------------------------------------------------

  ALTER TABLE "CONTESTOAPPLICATIVO" ADD CONSTRAINT "CONTESTOAPPLICATIVO_PK" PRIMARY KEY ("CONTESTOAPPLICATIVO_ID") USING INDEX  ENABLE
  ALTER TABLE "CONTESTOAPPLICATIVO" ADD CONSTRAINT "CONTESTOAPPLICATIVO_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "CONTESTOAPPLICATIVO" ADD CONSTRAINT "CONTESTOAPPLICATIVO_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
  ALTER TABLE "CONTESTOAPPLICATIVO" MODIFY ("CONTESTOAPPLICATIVO_ID" NOT NULL ENABLE)
  ALTER TABLE "CONTESTOAPPLICATIVO" MODIFY ("ENABLED" NOT NULL ENABLE)
  ALTER TABLE "CONTESTOAPPLICATIVO" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "CONTESTOAPPLICATIVO" ADD CHECK (ENABLED IN (1,0)) ENABLE
