--------------------------------------------------------
--  Constraints for Table CONTRATTOAPP
--------------------------------------------------------

  ALTER TABLE "CONTRATTOAPP" ADD CONSTRAINT "CONTRATTIAPPLICAIZONI_UNQ" UNIQUE ("CONTRATTO_CONTRATTO_ID_OID", "APPLICAZIONE_APPLICAZIONE_ID_OID") USING INDEX  ENABLE
  ALTER TABLE "CONTRATTOAPP" ADD CONSTRAINT "CONTRATTOAPP_PK" PRIMARY KEY ("CONTRATTO_APPLICAZIONE_ID") USING INDEX  ENABLE
  ALTER TABLE "CONTRATTOAPP" MODIFY ("CONTRATTO_APPLICAZIONE_ID" NOT NULL ENABLE)
  ALTER TABLE "CONTRATTOAPP" MODIFY ("VERSION" NOT NULL ENABLE)
