--------------------------------------------------------
--  Constraints for Table DATABASE
--------------------------------------------------------

  ALTER TABLE "DATABASE" ADD CONSTRAINT "DATABASES_UNQ" UNIQUE ("NAME", "AMBIENTESDLC_AMBIENTESDLC_ID_OID") USING INDEX  ENABLE
  ALTER TABLE "DATABASE" ADD CONSTRAINT "DATABASE_PK" PRIMARY KEY ("DATABASE_ID") USING INDEX  ENABLE
  ALTER TABLE "DATABASE" MODIFY ("DATABASE_ID" NOT NULL ENABLE)
  ALTER TABLE "DATABASE" MODIFY ("ATTIVO" NOT NULL ENABLE)
  ALTER TABLE "DATABASE" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "DATABASE" ADD CHECK (ATTIVO IN (1,0)) ENABLE
