--------------------------------------------------------
--  Constraints for Table DATABASEAPPCOMPARCH
--------------------------------------------------------

  ALTER TABLE "DATABASEAPPCOMPARCH" ADD CONSTRAINT "DATABASEAPPCOMPARCH_PK" PRIMARY KEY ("DATABASE_APPCOMPARCH_ID") USING INDEX  ENABLE
  ALTER TABLE "DATABASEAPPCOMPARCH" ADD CONSTRAINT "DATABASEAPPCOMPARCH_UNQ" UNIQUE ("DATABASE_DATABASE_ID_OID", "APPLICAZIONECOMPONENTEARCHITETTURA_APPLICAZIONE_COMPARCH_ID_OID") USING INDEX  ENABLE
  ALTER TABLE "DATABASEAPPCOMPARCH" MODIFY ("DATABASE_APPCOMPARCH_ID" NOT NULL ENABLE)
  ALTER TABLE "DATABASEAPPCOMPARCH" MODIFY ("VERSION" NOT NULL ENABLE)
