--------------------------------------------------------
--  Constraints for Table DATABASESERVTECNCOMPARCH
--------------------------------------------------------

  ALTER TABLE "DATABASESERVTECNCOMPARCH" ADD CONSTRAINT "DATABASESERVTECNCOMPARCH_PK" PRIMARY KEY ("DATABASE_SERVTECNCOMPARCH_ID") USING INDEX  ENABLE
  ALTER TABLE "DATABASESERVTECNCOMPARCH" ADD CONSTRAINT "DATABASESERVTECNCOMPARCH_UNQ" UNIQUE ("DATABASE_DATABASE_ID_OID", "SERVIZIOTECNICOCOMPONENTEARCHITETTURA_SERVIZIOTECNICO_COMPONENTE_ID_OID") USING INDEX  ENABLE
  ALTER TABLE "DATABASESERVTECNCOMPARCH" MODIFY ("DATABASE_SERVTECNCOMPARCH_ID" NOT NULL ENABLE)
  ALTER TABLE "DATABASESERVTECNCOMPARCH" MODIFY ("VERSION" NOT NULL ENABLE)
