--------------------------------------------------------
--  Constraints for Table DATODADB
--------------------------------------------------------

  ALTER TABLE "DATODADB" ADD CONSTRAINT "DATODADB_PK" PRIMARY KEY ("DATODADB_ID") USING INDEX  ENABLE
  ALTER TABLE "DATODADB" MODIFY ("DATODADB_ID" NOT NULL ENABLE)
  ALTER TABLE "DATODADB" MODIFY ("COLSNBR" NOT NULL ENABLE)
  ALTER TABLE "DATODADB" MODIFY ("INTESTAZIONE" NOT NULL ENABLE)
  ALTER TABLE "DATODADB" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "DATODADB" ADD CHECK (INTESTAZIONE IN (1,0)) ENABLE
