--------------------------------------------------------
--  Constraints for Table DATODADBRIGHETESTO
--------------------------------------------------------

  ALTER TABLE "DATODADBRIGHETESTO" ADD CONSTRAINT "DATODADBRIGHETESTO_PK" PRIMARY KEY ("DATODADB_RIGATESTO_ID") USING INDEX  ENABLE
  ALTER TABLE "DATODADBRIGHETESTO" MODIFY ("DATODADB_RIGATESTO_ID" NOT NULL ENABLE)
  ALTER TABLE "DATODADBRIGHETESTO" MODIFY ("ORDINE" NOT NULL ENABLE)
  ALTER TABLE "DATODADBRIGHETESTO" MODIFY ("VERSION" NOT NULL ENABLE)
