--------------------------------------------------------
--  Constraints for Table FUNZIONESA
--------------------------------------------------------

  ALTER TABLE "FUNZIONESA" ADD CONSTRAINT "FUNZIONESA_PK" PRIMARY KEY ("FUNZIONESA_ID") USING INDEX  ENABLE
  ALTER TABLE "FUNZIONESA" ADD CONSTRAINT "FUNZIONESA_UNQ1" UNIQUE ("APPLICAZIONESICUREZZAAPPLICATIVA_APPLICAZIONESA_ID_OID", "TIPOFUNZIONE", "NAME") USING INDEX  ENABLE
  ALTER TABLE "FUNZIONESA" MODIFY ("FUNZIONESA_ID" NOT NULL ENABLE)
  ALTER TABLE "FUNZIONESA" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "FUNZIONESA" ADD CHECK (DELETED IN (1,0) OR DELETED IS NULL) ENABLE
