--------------------------------------------------------
--  Constraints for Table GRUPPIMEMBRI
--------------------------------------------------------

  ALTER TABLE "GRUPPIMEMBRI" ADD CONSTRAINT "GRUPPIMEMBRI_PK" PRIMARY KEY ("GRUPPO_MEMBRI_ID") USING INDEX  ENABLE
  ALTER TABLE "GRUPPIMEMBRI" MODIFY ("GRUPPO_MEMBRI_ID" NOT NULL ENABLE)
  ALTER TABLE "GRUPPIMEMBRI" MODIFY ("UTENTEDN" NOT NULL ENABLE)
  ALTER TABLE "GRUPPIMEMBRI" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "GRUPPIMEMBRI" ADD CHECK (DELETED IN (1,0) OR DELETED IS NULL) ENABLE
