--------------------------------------------------------
--  Constraints for Table GRUPPO
--------------------------------------------------------

  ALTER TABLE "GRUPPO" ADD CONSTRAINT "GRUPPO_NOME_UNQ" UNIQUE ("NOME") USING INDEX  ENABLE
  ALTER TABLE "GRUPPO" ADD CONSTRAINT "GRUPPO_PK" PRIMARY KEY ("GRUPPO_ID") USING INDEX  ENABLE
  ALTER TABLE "GRUPPO" MODIFY ("GRUPPO_ID" NOT NULL ENABLE)
  ALTER TABLE "GRUPPO" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "GRUPPO" ADD CHECK (DELETED IN (1,0) OR DELETED IS NULL) ENABLE
