--------------------------------------------------------
--  Constraints for Table PIATTAFAPPCOMPARCH
--------------------------------------------------------

  ALTER TABLE "PIATTAFAPPCOMPARCH" ADD CONSTRAINT "PIATTAFAPPCOMPARCH_PK" PRIMARY KEY ("PIATTAF_APPCOMPARCH_ID") USING INDEX  ENABLE
  ALTER TABLE "PIATTAFAPPCOMPARCH" ADD CONSTRAINT "PIATTAFAPPCOMPARCH_UNQ" UNIQUE ("PIATTAFORMA_PIATTAFORMA_ID_OID", "APPLICAZIONECOMPONENTEARCHITETTURA_APPLICAZIONE_COMPARCH_ID_OID") USING INDEX  ENABLE
  ALTER TABLE "PIATTAFAPPCOMPARCH" MODIFY ("PIATTAF_APPCOMPARCH_ID" NOT NULL ENABLE)
  ALTER TABLE "PIATTAFAPPCOMPARCH" MODIFY ("VERSION" NOT NULL ENABLE)
