--------------------------------------------------------
--  Constraints for Table PIATTAFSERVTECNCOMPARCH
--------------------------------------------------------

  ALTER TABLE "PIATTAFSERVTECNCOMPARCH" ADD CONSTRAINT "PIATTAFSERVTECNCOMPARCH_PK" PRIMARY KEY ("PIATTAF_SERVTECNCOMPARCH_ID") USING INDEX  ENABLE
  ALTER TABLE "PIATTAFSERVTECNCOMPARCH" ADD CONSTRAINT "PIATTAFSERVTECNCOMPARCH_UNQ" UNIQUE ("PIATTAFORMA_PIATTAFORMA_ID_OID", "SERVIZIOTECNICOCOMPONENTEARCHITETTURA_SERVIZIOTECNICO_COMPONENTE_ID_OID") USING INDEX  ENABLE
  ALTER TABLE "PIATTAFSERVTECNCOMPARCH" MODIFY ("PIATTAF_SERVTECNCOMPARCH_ID" NOT NULL ENABLE)
  ALTER TABLE "PIATTAFSERVTECNCOMPARCH" MODIFY ("VERSION" NOT NULL ENABLE)
