--------------------------------------------------------
--  Constraints for Table PIATTAFORMA
--------------------------------------------------------

  ALTER TABLE "PIATTAFORMA" ADD CONSTRAINT "PIATTAFORMA_PK" PRIMARY KEY ("PIATTAFORMA_ID") USING INDEX  ENABLE
  ALTER TABLE "PIATTAFORMA" ADD CONSTRAINT "PIATTAFORMA_UNQ" UNIQUE ("NOME", "AMBIENTESDLC_AMBIENTESDLC_ID_OID") USING INDEX  ENABLE
  ALTER TABLE "PIATTAFORMA" MODIFY ("PIATTAFORMA_ID" NOT NULL ENABLE)
  ALTER TABLE "PIATTAFORMA" MODIFY ("ATTIVO" NOT NULL ENABLE)
  ALTER TABLE "PIATTAFORMA" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "PIATTAFORMA" ADD CHECK (ATTIVO IN (1,0)) ENABLE
