--------------------------------------------------------
--  Constraints for Table RECORDOFPROCESSINGACTIVITY
--------------------------------------------------------

  ALTER TABLE "RECORDOFPROCESSINGACTIVITY" ADD CONSTRAINT "RECORDOFPROCESSINGACTIVITY_PK" PRIMARY KEY ("ROPA_ID") USING INDEX  ENABLE
  ALTER TABLE "RECORDOFPROCESSINGACTIVITY" MODIFY ("ROPA_ID" NOT NULL ENABLE)
  ALTER TABLE "RECORDOFPROCESSINGACTIVITY" MODIFY ("ESITO" NOT NULL ENABLE)
  ALTER TABLE "RECORDOFPROCESSINGACTIVITY" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "RECORDOFPROCESSINGACTIVITY" ADD CHECK (ESITO IN (1,0)) ENABLE
