--------------------------------------------------------
--  Constraints for Table RESPONSABILEAPPLICATIVO
--------------------------------------------------------

  ALTER TABLE "RESPONSABILEAPPLICATIVO" ADD CONSTRAINT "RESPONSABILEAPPLICATIVO_PK" PRIMARY KEY ("RESPONSABILEAPPLICATIVO_ID") USING INDEX  ENABLE
  ALTER TABLE "RESPONSABILEAPPLICATIVO" ADD CONSTRAINT "RESPONSABILEAPPLICATIVO_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "RESPONSABILEAPPLICATIVO" ADD CONSTRAINT "RESPONSABILEAPPLICATIVO_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
  ALTER TABLE "RESPONSABILEAPPLICATIVO" MODIFY ("RESPONSABILEAPPLICATIVO_ID" NOT NULL ENABLE)
  ALTER TABLE "RESPONSABILEAPPLICATIVO" MODIFY ("ENABLED" NOT NULL ENABLE)
  ALTER TABLE "RESPONSABILEAPPLICATIVO" MODIFY ("TECNICO" NOT NULL ENABLE)
  ALTER TABLE "RESPONSABILEAPPLICATIVO" MODIFY ("TERZO" NOT NULL ENABLE)
  ALTER TABLE "RESPONSABILEAPPLICATIVO" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "RESPONSABILEAPPLICATIVO" ADD CHECK (ENABLED IN (1,0)) ENABLE
  ALTER TABLE "RESPONSABILEAPPLICATIVO" ADD CHECK (TECNICO IN (1,0)) ENABLE
  ALTER TABLE "RESPONSABILEAPPLICATIVO" ADD CHECK (TERZO IN (1,0)) ENABLE
