--------------------------------------------------------
--  Constraints for Table ROPARIGHETESTO
--------------------------------------------------------

  ALTER TABLE "ROPARIGHETESTO" ADD CONSTRAINT "ROPARIGHETESTO_PK" PRIMARY KEY ("ROPA_RIGATESTO_ID") USING INDEX  ENABLE
  ALTER TABLE "ROPARIGHETESTO" MODIFY ("ROPA_RIGATESTO_ID" NOT NULL ENABLE)
  ALTER TABLE "ROPARIGHETESTO" MODIFY ("ORDINE" NOT NULL ENABLE)
  ALTER TABLE "ROPARIGHETESTO" MODIFY ("VERSION" NOT NULL ENABLE)
