--------------------------------------------------------
--  Constraints for Table RUOLOSA
--------------------------------------------------------

  ALTER TABLE "RUOLOSA" ADD CONSTRAINT "RUOLOSA_PK" PRIMARY KEY ("RUOLOSA_ID") USING INDEX  ENABLE
  ALTER TABLE "RUOLOSA" ADD CONSTRAINT "RUOLOSA_UNQ1" UNIQUE ("APPLICAZIONESICUREZZAAPPLICATIVA_APPLICAZIONESA_ID_OID", "NAME") USING INDEX  ENABLE
  ALTER TABLE "RUOLOSA" MODIFY ("RUOLOSA_ID" NOT NULL ENABLE)
  ALTER TABLE "RUOLOSA" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "RUOLOSA" ADD CHECK (DELETED IN (1,0) OR DELETED IS NULL) ENABLE
