--------------------------------------------------------
--  Constraints for Table RUOLIFUNZIONISA
--------------------------------------------------------

  ALTER TABLE "RUOLIFUNZIONISA" ADD CONSTRAINT "RUOLIFUNZIONISA_PK" PRIMARY KEY ("RUOLOSA_ID", "FUNZIONESA_ID") USING INDEX  ENABLE
  ALTER TABLE "RUOLIFUNZIONISA" MODIFY ("RUOLOSA_ID" NOT NULL ENABLE)
  ALTER TABLE "RUOLIFUNZIONISA" MODIFY ("FUNZIONESA_ID" NOT NULL ENABLE)
