--------------------------------------------------------
--  Constraints for Table SERVIZITECNICISERVTEC
--------------------------------------------------------

  ALTER TABLE "SERVIZITECNICISERVTEC" ADD CONSTRAINT "SERVIZITECNICISERVTEC_PK" PRIMARY KEY ("SERVIZIOTECNICO_SERVTEC_ID") USING INDEX  ENABLE
  ALTER TABLE "SERVIZITECNICISERVTEC" ADD CONSTRAINT "SERVIZITECNICISERVTEC_UNQ" UNIQUE ("SERVIZIOTECNICO_SERVIZIO_ID_OID", "SERVIZIOTECNICOREF_SERVIZIO_ID_OID", "NONPIF9INUSO") USING INDEX  ENABLE
  ALTER TABLE "SERVIZITECNICISERVTEC" MODIFY ("SERVIZIOTECNICO_SERVTEC_ID" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICISERVTEC" MODIFY ("NONPIF9INUSO" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICISERVTEC" MODIFY ("SERVIZIOTECNICO_SERVIZIO_ID_OID" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICISERVTEC" MODIFY ("SERVIZIOTECNICOREF_SERVIZIO_ID_OID" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICISERVTEC" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICISERVTEC" ADD CHECK (NONPIF9INUSO IN (1,0)) ENABLE
