--------------------------------------------------------
--  Constraints for Table SERVIZITECNICIVERSIONI
--------------------------------------------------------

  ALTER TABLE "SERVIZITECNICIVERSIONI" ADD CONSTRAINT "SERVIZITECNICIVERSIONI_PK" PRIMARY KEY ("SERVIZIOTECNICO_VERSIONI_ID") USING INDEX  ENABLE
  ALTER TABLE "SERVIZITECNICIVERSIONI" ADD CONSTRAINT "SERVIZITECNICIVERSIONI_UNQ" UNIQUE ("SERVIZIOTECNICO_SERVIZIO_ID_OID", "TAG") USING INDEX  ENABLE
  ALTER TABLE "SERVIZITECNICIVERSIONI" MODIFY ("SERVIZIOTECNICO_VERSIONI_ID" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICIVERSIONI" MODIFY ("SERVIZIOTECNICO_SERVIZIO_ID_OID" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICIVERSIONI" MODIFY ("VERSION" NOT NULL ENABLE)
