--------------------------------------------------------
--  Constraints for Table SERVIZITECNICIAPP
--------------------------------------------------------

  ALTER TABLE "SERVIZITECNICIAPP" ADD CONSTRAINT "SERVIZITECNICIAPP_PK" PRIMARY KEY ("SERVIZIOTECNICO_APP_ID") USING INDEX  ENABLE
  ALTER TABLE "SERVIZITECNICIAPP" ADD CONSTRAINT "SERVIZITECNICIAPP_UNQ" UNIQUE ("SERVIZIOTECNICO_SERVIZIO_ID_OID", "APPLICAZIONE_APPLICAZIONE_ID_OID", "NONPIF9INUSO") USING INDEX  ENABLE
  ALTER TABLE "SERVIZITECNICIAPP" MODIFY ("SERVIZIOTECNICO_APP_ID" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICIAPP" MODIFY ("APPLICAZIONE_APPLICAZIONE_ID_OID" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICIAPP" MODIFY ("NONPIF9INUSO" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICIAPP" MODIFY ("SERVIZIOTECNICO_SERVIZIO_ID_OID" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICIAPP" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICIAPP" ADD CHECK (NONPIF9INUSO IN (1,0)) ENABLE
