--------------------------------------------------------
--  Constraints for Table SERVIZITECNICICOMPARCH
--------------------------------------------------------

  ALTER TABLE "SERVIZITECNICICOMPARCH" ADD CONSTRAINT "SERVIZITECNICICOMPARCH_PK" PRIMARY KEY ("SERVIZIOTECNICO_COMPONENTE_ID") USING INDEX  ENABLE
  ALTER TABLE "SERVIZITECNICICOMPARCH" ADD CONSTRAINT "SERVIZITECNICICOMPARCH_UNQ" UNIQUE ("SERVIZIOTECNICO_SERVIZIO_ID_OID", "TIPOCOMPONENTE_TIPOCOMPONENTESERVIZI_ID_OID", "TECNOLOGIASW_TECNOLOGIASWSERVIZI_ID_OID", "URIREPOSITORY", "NONPIF9INUSO") USING INDEX  ENABLE
  ALTER TABLE "SERVIZITECNICICOMPARCH" MODIFY ("SERVIZIOTECNICO_COMPONENTE_ID" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICICOMPARCH" MODIFY ("URIREPOSITORY" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICICOMPARCH" MODIFY ("DESCRIZIONE" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICICOMPARCH" MODIFY ("DETTAGLITECNOLOGIASW" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICICOMPARCH" MODIFY ("NONPIF9INUSO" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICICOMPARCH" MODIFY ("TECNOLOGIASW_TECNOLOGIASWSERVIZI_ID_OID" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICICOMPARCH" MODIFY ("TIPOCOMPONENTE_TIPOCOMPONENTESERVIZI_ID_OID" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICICOMPARCH" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICICOMPARCH" ADD CHECK (NONPIF9INUSO IN (1,0)) ENABLE
