--------------------------------------------------------
--  Constraints for Table SERVER
--------------------------------------------------------

  ALTER TABLE "SERVER" ADD CONSTRAINT "SERVER_PK" PRIMARY KEY ("SERVER_ID") USING INDEX  ENABLE
  ALTER TABLE "SERVER" ADD CONSTRAINT "SERVER_UNQ" UNIQUE ("HOST") USING INDEX  ENABLE
  ALTER TABLE "SERVER" MODIFY ("SERVER_ID" NOT NULL ENABLE)
  ALTER TABLE "SERVER" MODIFY ("ATTIVO" NOT NULL ENABLE)
  ALTER TABLE "SERVER" MODIFY ("DISMESSO" NOT NULL ENABLE)
  ALTER TABLE "SERVER" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "SERVER" ADD CHECK (ATTIVO IN (1,0)) ENABLE
  ALTER TABLE "SERVER" ADD CHECK (DISMESSO IN (1,0)) ENABLE
