--------------------------------------------------------
--  Constraints for Table SERVIZIOTECNICO
--------------------------------------------------------

  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_NOME_UNQ" UNIQUE ("NOME") USING INDEX  ENABLE
  ALTER TABLE "SERVIZIOTECNICO" ADD CONSTRAINT "SERVIZIOTECNICO_PK" PRIMARY KEY ("SERVIZIO_ID") USING INDEX  ENABLE
  ALTER TABLE "SERVIZIOTECNICO" MODIFY ("SERVIZIO_ID" NOT NULL ENABLE)
  ALTER TABLE "SERVIZIOTECNICO" MODIFY ("DASOTTOPORREASOFTWAREANALYTICS" NOT NULL ENABLE)
  ALTER TABLE "SERVIZIOTECNICO" MODIFY ("DISMESSA" NOT NULL ENABLE)
  ALTER TABLE "SERVIZIOTECNICO" MODIFY ("NOME" NOT NULL ENABLE)
  ALTER TABLE "SERVIZIOTECNICO" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "SERVIZIOTECNICO" ADD CHECK (DASOTTOPORREASOFTWAREANALYTICS IN (1,0)) ENABLE
  ALTER TABLE "SERVIZIOTECNICO" ADD CHECK (DISMESSA IN (1,0)) ENABLE
