--------------------------------------------------------
--  Constraints for Table SERVIZITECNICIENDPOINTS
--------------------------------------------------------

  ALTER TABLE "SERVIZITECNICIENDPOINTS" ADD CONSTRAINT "SERVIZITECNICIENDPOINTS_PK" PRIMARY KEY ("SERVIZIOTECNICO_ENDPOINT_ID") USING INDEX  ENABLE
  ALTER TABLE "SERVIZITECNICIENDPOINTS" ADD CONSTRAINT "SERVIZITECNICIENDPOINTS_UNQ" UNIQUE ("SERVIZIOTECNICO_SERVIZIO_ID_OID", "TIPOENDPOINT_TIPOENDPOINTSERVIZI_ID_OID", "ENDPOINT", "NONPIUINUSO") USING INDEX  ENABLE
  ALTER TABLE "SERVIZITECNICIENDPOINTS" MODIFY ("SERVIZIOTECNICO_ENDPOINT_ID" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICIENDPOINTS" MODIFY ("DESCRIZIONE" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICIENDPOINTS" MODIFY ("ENDPOINT" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICIENDPOINTS" MODIFY ("NONPIUINUSO" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICIENDPOINTS" MODIFY ("TIPOENDPOINT_TIPOENDPOINTSERVIZI_ID_OID" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICIENDPOINTS" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "SERVIZITECNICIENDPOINTS" ADD CHECK (NONPIUINUSO IN (1,0)) ENABLE
