--------------------------------------------------------
--  Constraints for Table SHARE
--------------------------------------------------------

  ALTER TABLE "SHARE" ADD CONSTRAINT "SHARE_PK" PRIMARY KEY ("SHARE_ID") USING INDEX  ENABLE
  ALTER TABLE "SHARE" MODIFY ("SHARE_ID" NOT NULL ENABLE)
  ALTER TABLE "SHARE" MODIFY ("INHERITED" NOT NULL ENABLE)
  ALTER TABLE "SHARE" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "SHARE" ADD CHECK (DELETED IN (1,0) OR DELETED IS NULL) ENABLE
  ALTER TABLE "SHARE" ADD CHECK (INDUBBIO IN (1,0) OR INDUBBIO IS NULL) ENABLE
  ALTER TABLE "SHARE" ADD CHECK (INHERITED IN (1,0)) ENABLE
