--------------------------------------------------------
--  Constraints for Table TABELLADBDATIPERSONALI
--------------------------------------------------------

  ALTER TABLE "TABELLADBDATIPERSONALI" MODIFY ("TABELLADBDATIPERSONALI_ID" NOT NULL ENABLE)
  ALTER TABLE "TABELLADBDATIPERSONALI" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TABELLADBDATIPERSONALI" ADD CONSTRAINT "TABELLADBDATIPERSONALI_PK" PRIMARY KEY ("TABELLADBDATIPERSONALI_ID") USING INDEX  ENABLE
  ALTER TABLE "TABELLADBDATIPERSONALI" ADD CONSTRAINT "TABELLADBDATIPERSONALI_UNQ1" UNIQUE ("NAME", "ORDER") USING INDEX  ENABLE
