--------------------------------------------------------
--  Constraints for Table TECHDATABASE
--------------------------------------------------------

  ALTER TABLE "TECHDATABASE" MODIFY ("TECHDATABASE_ID" NOT NULL ENABLE)
  ALTER TABLE "TECHDATABASE" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TECHDATABASE" ADD CONSTRAINT "TECHDATABASE_PK" PRIMARY KEY ("TECHDATABASE_ID") USING INDEX  ENABLE
  ALTER TABLE "TECHDATABASE" ADD CONSTRAINT "TECHDATABASE_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TECHDATABASE" ADD CONSTRAINT "TECHDATABASE_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
