--------------------------------------------------------
--  Constraints for Table TECNOLOGIASW
--------------------------------------------------------

  ALTER TABLE "TECNOLOGIASW" MODIFY ("TECNOLOGIASW_ID" NOT NULL ENABLE)
  ALTER TABLE "TECNOLOGIASW" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TECNOLOGIASW" ADD CONSTRAINT "TECNOLOGIASW_PK" PRIMARY KEY ("TECNOLOGIASW_ID") USING INDEX  ENABLE
  ALTER TABLE "TECNOLOGIASW" ADD CONSTRAINT "TECNOLOGIASW_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TECNOLOGIASW" ADD CONSTRAINT "TECNOLOGIASW_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
