--------------------------------------------------------
--  Constraints for Table TECNOLOGIASWSERVIZI
--------------------------------------------------------

  ALTER TABLE "TECNOLOGIASWSERVIZI" MODIFY ("TECNOLOGIASWSERVIZI_ID" NOT NULL ENABLE)
  ALTER TABLE "TECNOLOGIASWSERVIZI" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TECNOLOGIASWSERVIZI" ADD CONSTRAINT "TECNOLOGIASWSERVIZI_PK" PRIMARY KEY ("TECNOLOGIASWSERVIZI_ID") USING INDEX  ENABLE
  ALTER TABLE "TECNOLOGIASWSERVIZI" ADD CONSTRAINT "TECNOLOGIASWSERVIZI_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TECNOLOGIASWSERVIZI" ADD CONSTRAINT "TECNOLOGIASWSERVIZI_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
