--------------------------------------------------------
--  Constraints for Table TIPOASSET
--------------------------------------------------------

  ALTER TABLE "TIPOASSET" MODIFY ("TIPOASSET_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOASSET" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOASSET" ADD CONSTRAINT "TIPOASSET_PK" PRIMARY KEY ("TIPOASSET_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOASSET" ADD CONSTRAINT "TIPOASSET_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOASSET" ADD CONSTRAINT "TIPOASSET_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
