--------------------------------------------------------
--  Constraints for Table TIPOGRUPPO
--------------------------------------------------------

  ALTER TABLE "TIPOGRUPPO" MODIFY ("TIPOGRUPPO_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOGRUPPO" MODIFY ("DAASSEGNARE" NOT NULL ENABLE)
  ALTER TABLE "TIPOGRUPPO" MODIFY ("TECNICO" NOT NULL ENABLE)
  ALTER TABLE "TIPOGRUPPO" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOGRUPPO" ADD CHECK (DAASSEGNARE IN (1,0)) ENABLE
  ALTER TABLE "TIPOGRUPPO" ADD CHECK (TECNICO IN (1,0)) ENABLE
  ALTER TABLE "TIPOGRUPPO" ADD CONSTRAINT "TIPOGRUPPO_PK" PRIMARY KEY ("TIPOGRUPPO_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOGRUPPO" ADD CONSTRAINT "TIPOGRUPPO_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOGRUPPO" ADD CONSTRAINT "TIPOGRUPPO_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
