--------------------------------------------------------
--  Constraints for Table TIPOENDPOINT
--------------------------------------------------------

  ALTER TABLE "TIPOENDPOINT" MODIFY ("TIPOENDPOINTSERVIZI_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOENDPOINT" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOENDPOINT" ADD CONSTRAINT "TIPOENDPOINTSERVIZI_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOENDPOINT" ADD CONSTRAINT "TIPOENDPOINTSERVIZI_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOENDPOINT" ADD CONSTRAINT "TIPOENDPOINT_PK" PRIMARY KEY ("TIPOENDPOINTSERVIZI_ID") USING INDEX  ENABLE
