--------------------------------------------------------
--  Constraints for Table TIPOINSTALLAZIONESUDISP
--------------------------------------------------------

  ALTER TABLE "TIPOINSTALLAZIONESUDISP" MODIFY ("TIPOINSTALLAZIONESUDISP_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOINSTALLAZIONESUDISP" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOINSTALLAZIONESUDISP" ADD CONSTRAINT "TIPOINSTALLAZIONESUDISP_PK" PRIMARY KEY ("TIPOINSTALLAZIONESUDISP_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOINSTALLAZIONESUDISP" ADD CONSTRAINT "TIPOINSTALLAZIONESUDISP_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOINSTALLAZIONESUDISP" ADD CONSTRAINT "TIPOINSTALLAZIONESUDISP_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
