--------------------------------------------------------
--  Constraints for Table TIPOSCM
--------------------------------------------------------

  ALTER TABLE "TIPOSCM" MODIFY ("TIPOSCM_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOSCM" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOSCM" ADD CONSTRAINT "TIPOSCM_PK" PRIMARY KEY ("TIPOSCM_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOSCM" ADD CONSTRAINT "TIPOSCM_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOSCM" ADD CONSTRAINT "TIPOSCM_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
