--------------------------------------------------------
--  Constraints for Table TIPOSSO
--------------------------------------------------------

  ALTER TABLE "TIPOSSO" MODIFY ("TIPOSSO_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOSSO" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOSSO" ADD CONSTRAINT "TIPOSSO_PK" PRIMARY KEY ("TIPOSSO_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOSSO" ADD CONSTRAINT "TIPOSSO_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOSSO" ADD CONSTRAINT "TIPOSSO_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
