--------------------------------------------------------
--  Constraints for Table TIPOAUTORIZZAZIONE
--------------------------------------------------------

  ALTER TABLE "TIPOAUTORIZZAZIONE" MODIFY ("TIPOAUTORIZZAZIONE_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOAUTORIZZAZIONE" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOAUTORIZZAZIONE" ADD CONSTRAINT "TIPOAUTORIZZAZIONE_PK" PRIMARY KEY ("TIPOAUTORIZZAZIONE_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOAUTORIZZAZIONE" ADD CONSTRAINT "TIPOAUTORIZZAZIONE_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOAUTORIZZAZIONE" ADD CONSTRAINT "TIPOAUTORIZZAZIONE_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
