--------------------------------------------------------
--  Constraints for Table TIPOUTENTETECNICO
--------------------------------------------------------

  ALTER TABLE "TIPOUTENTETECNICO" MODIFY ("TIPOUTENTETECNICO_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOUTENTETECNICO" MODIFY ("CONALTIPRIVILEGI" NOT NULL ENABLE)
  ALTER TABLE "TIPOUTENTETECNICO" MODIFY ("PERATTIVITA" NOT NULL ENABLE)
  ALTER TABLE "TIPOUTENTETECNICO" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOUTENTETECNICO" ADD CHECK (CONALTIPRIVILEGI IN (1,0)) ENABLE
  ALTER TABLE "TIPOUTENTETECNICO" ADD CHECK (PERATTIVITA IN (1,0)) ENABLE
  ALTER TABLE "TIPOUTENTETECNICO" ADD CONSTRAINT "TIPOUTENTETECNICO_PK" PRIMARY KEY ("TIPOUTENTETECNICO_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOUTENTETECNICO" ADD CONSTRAINT "TIPOUTENTETECNICO_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOUTENTETECNICO" ADD CONSTRAINT "TIPOUTENTETECNICO_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
