--------------------------------------------------------
--  Constraints for Table TIPOINFRASTRUTTURAASUPP
--------------------------------------------------------

  ALTER TABLE "TIPOINFRASTRUTTURAASUPP" MODIFY ("TIPOINFRASTRUTTURAASUPPORTO_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOINFRASTRUTTURAASUPP" MODIFY ("RESPONSABILITARP" NOT NULL ENABLE)
  ALTER TABLE "TIPOINFRASTRUTTURAASUPP" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOINFRASTRUTTURAASUPP" ADD CHECK (RESPONSABILITARP IN (1,0)) ENABLE
  ALTER TABLE "TIPOINFRASTRUTTURAASUPP" ADD CONSTRAINT "TIPOINFRASTRUTTURAASUPP_PK" PRIMARY KEY ("TIPOINFRASTRUTTURAASUPPORTO_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOINFRASTRUTTURAASUPP" ADD CONSTRAINT "TIPOINFRASTRUTTURAASUPP_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOINFRASTRUTTURAASUPP" ADD CONSTRAINT "TIPOINFRASTRUTTURAASUPP_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
