--------------------------------------------------------
--  Constraints for Table TIPOSERVIZIOTECNICO
--------------------------------------------------------

  ALTER TABLE "TIPOSERVIZIOTECNICO" MODIFY ("TIPOSERVIZIOTECNICO_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOSERVIZIOTECNICO" MODIFY ("GOVERNOINFRAAPPLICATIVA" NOT NULL ENABLE)
  ALTER TABLE "TIPOSERVIZIOTECNICO" MODIFY ("SERVIZIOTECNICODITERZI" NOT NULL ENABLE)
  ALTER TABLE "TIPOSERVIZIOTECNICO" MODIFY ("SOFTWAREANALITYCS" NOT NULL ENABLE)
  ALTER TABLE "TIPOSERVIZIOTECNICO" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOSERVIZIOTECNICO" ADD CHECK (GOVERNOINFRAAPPLICATIVA IN (1,0)) ENABLE
  ALTER TABLE "TIPOSERVIZIOTECNICO" ADD CHECK (SERVIZIOTECNICODITERZI IN (1,0)) ENABLE
  ALTER TABLE "TIPOSERVIZIOTECNICO" ADD CHECK (SOFTWAREANALITYCS IN (1,0)) ENABLE
  ALTER TABLE "TIPOSERVIZIOTECNICO" ADD CONSTRAINT "TIPOSERVIZIOTECNICO_PK" PRIMARY KEY ("TIPOSERVIZIOTECNICO_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOSERVIZIOTECNICO" ADD CONSTRAINT "TIPOSERVIZIOTECNICO_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOSERVIZIOTECNICO" ADD CONSTRAINT "TIPOSERVIZIOTECNICO_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
