--------------------------------------------------------
--  Constraints for Table TIPOFRUIZIONE
--------------------------------------------------------

  ALTER TABLE "TIPOFRUIZIONE" MODIFY ("TIPOFRUIZIONE_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOFRUIZIONE" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOFRUIZIONE" ADD CONSTRAINT "TIPOFRUIZIONE_PK" PRIMARY KEY ("TIPOFRUIZIONE_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOFRUIZIONE" ADD CONSTRAINT "TIPOFRUIZIONE_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOFRUIZIONE" ADD CONSTRAINT "TIPOFRUIZIONE_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
