--------------------------------------------------------
--  Constraints for Table TIPOIDENTITA
--------------------------------------------------------

  ALTER TABLE "TIPOIDENTITA" MODIFY ("TIPOIDENTITA_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOIDENTITA" MODIFY ("DEVEAVEREUO" NOT NULL ENABLE)
  ALTER TABLE "TIPOIDENTITA" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOIDENTITA" ADD CHECK (DEVEAVEREUO IN (1,0)) ENABLE
  ALTER TABLE "TIPOIDENTITA" ADD CONSTRAINT "TIPOIDENTITA_PK" PRIMARY KEY ("TIPOIDENTITA_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOIDENTITA" ADD CONSTRAINT "TIPOIDENTITA_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOIDENTITA" ADD CONSTRAINT "TIPOIDENTITA_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
