--------------------------------------------------------
--  Constraints for Table TIPOSDL2
--------------------------------------------------------

  ALTER TABLE "TIPOSDL2" MODIFY ("TIPOSDL2_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOSDL2" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOSDL2" ADD CONSTRAINT "TIPOSDL2_PK" PRIMARY KEY ("TIPOSDL2_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOSDL2" ADD CONSTRAINT "TIPOSDL2_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOSDL2" ADD CONSTRAINT "TIPOSDL2_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
