--------------------------------------------------------
--  Constraints for Table TIPOINDICE3
--------------------------------------------------------

  ALTER TABLE "TIPOINDICE3" MODIFY ("TIPOINDICE3_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOINDICE3" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOINDICE3" ADD CONSTRAINT "TIPOINDICE3_PK" PRIMARY KEY ("TIPOINDICE3_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOINDICE3" ADD CONSTRAINT "TIPOINDICE3_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOINDICE3" ADD CONSTRAINT "TIPOINDICE3_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
