--------------------------------------------------------
--  Constraints for Table TIPOAUTENTICAZIONE
--------------------------------------------------------

  ALTER TABLE "TIPOAUTENTICAZIONE" MODIFY ("TIPOAUTENTICAZIONE_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOAUTENTICAZIONE" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOAUTENTICAZIONE" ADD CONSTRAINT "TIPOAUTENTICAZIONE_PK" PRIMARY KEY ("TIPOAUTENTICAZIONE_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOAUTENTICAZIONE" ADD CONSTRAINT "TIPOAUTENTICAZIONE_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOAUTENTICAZIONE" ADD CONSTRAINT "TIPOAUTENTICAZIONE_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
