--------------------------------------------------------
--  Constraints for Table TIPOAPPLICAZIONE
--------------------------------------------------------

  ALTER TABLE "TIPOAPPLICAZIONE" MODIFY ("TIPOAPPLICAZIONE_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOAPPLICAZIONE" MODIFY ("AMBIENTISDLCSCM" NOT NULL ENABLE)
  ALTER TABLE "TIPOAPPLICAZIONE" MODIFY ("APPLICAZIONEDITERZI" NOT NULL ENABLE)
  ALTER TABLE "TIPOAPPLICAZIONE" MODIFY ("COMPONENTISCM" NOT NULL ENABLE)
  ALTER TABLE "TIPOAPPLICAZIONE" MODIFY ("CONTRATTOAMIT" NOT NULL ENABLE)
  ALTER TABLE "TIPOAPPLICAZIONE" MODIFY ("GOVERNOINFRAAPPLICATIVA" NOT NULL ENABLE)
  ALTER TABLE "TIPOAPPLICAZIONE" MODIFY ("REPOSITORYSCM" NOT NULL ENABLE)
  ALTER TABLE "TIPOAPPLICAZIONE" MODIFY ("SOFTWAREANALITYCS" NOT NULL ENABLE)
  ALTER TABLE "TIPOAPPLICAZIONE" MODIFY ("VERSIONISCM" NOT NULL ENABLE)
  ALTER TABLE "TIPOAPPLICAZIONE" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOAPPLICAZIONE" ADD CHECK (AMBIENTISDLCSCM IN (1,0)) ENABLE
  ALTER TABLE "TIPOAPPLICAZIONE" ADD CHECK (APPLICAZIONEDITERZI IN (1,0)) ENABLE
  ALTER TABLE "TIPOAPPLICAZIONE" ADD CHECK (COMPONENTISCM IN (1,0)) ENABLE
  ALTER TABLE "TIPOAPPLICAZIONE" ADD CHECK (CONTRATTOAMIT IN (1,0)) ENABLE
  ALTER TABLE "TIPOAPPLICAZIONE" ADD CHECK (GOVERNOINFRAAPPLICATIVA IN (1,0)) ENABLE
  ALTER TABLE "TIPOAPPLICAZIONE" ADD CHECK (REPOSITORYSCM IN (1,0)) ENABLE
  ALTER TABLE "TIPOAPPLICAZIONE" ADD CHECK (SOFTWAREANALITYCS IN (1,0)) ENABLE
  ALTER TABLE "TIPOAPPLICAZIONE" ADD CHECK (VERSIONISCM IN (1,0)) ENABLE
  ALTER TABLE "TIPOAPPLICAZIONE" ADD CONSTRAINT "TIPOAPPLICAZIONE_PK" PRIMARY KEY ("TIPOAPPLICAZIONE_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOAPPLICAZIONE" ADD CONSTRAINT "TIPOAPPLICAZIONE_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOAPPLICAZIONE" ADD CONSTRAINT "TIPOAPPLICAZIONE_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
