--------------------------------------------------------
--  Constraints for Table TIPODATABASE
--------------------------------------------------------

  ALTER TABLE "TIPODATABASE" MODIFY ("TIPODATABASE_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPODATABASE" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPODATABASE" ADD CONSTRAINT "TIPODATABASE_PK" PRIMARY KEY ("TIPODATABASE_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPODATABASE" ADD CONSTRAINT "TIPODATABASE_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPODATABASE" ADD CONSTRAINT "TIPODATABASE_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
