--------------------------------------------------------
--  Constraints for Table TIPOUTENTE
--------------------------------------------------------

  ALTER TABLE "TIPOUTENTE" MODIFY ("TIPOUTENTE_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOUTENTE" MODIFY ("DEVEAVEREIDENTITA" NOT NULL ENABLE)
  ALTER TABLE "TIPOUTENTE" MODIFY ("IDENTITADAASSEGNARE" NOT NULL ENABLE)
  ALTER TABLE "TIPOUTENTE" MODIFY ("TIPOUTENTETECNICODAASSEGNARE" NOT NULL ENABLE)
  ALTER TABLE "TIPOUTENTE" MODIFY ("UTENTEAPPLICATIVO" NOT NULL ENABLE)
  ALTER TABLE "TIPOUTENTE" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOUTENTE" ADD CHECK (DEVEAVEREIDENTITA IN (1,0)) ENABLE
  ALTER TABLE "TIPOUTENTE" ADD CHECK (IDENTITADAASSEGNARE IN (1,0)) ENABLE
  ALTER TABLE "TIPOUTENTE" ADD CHECK (TIPOUTENTETECNICODAASSEGNARE IN (1,0)) ENABLE
  ALTER TABLE "TIPOUTENTE" ADD CHECK (UTENTEAPPLICATIVO IN (1,0)) ENABLE
  ALTER TABLE "TIPOUTENTE" ADD CONSTRAINT "TIPOUTENTE_PK" PRIMARY KEY ("TIPOUTENTE_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOUTENTE" ADD CONSTRAINT "TIPOUTENTE_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOUTENTE" ADD CONSTRAINT "TIPOUTENTE_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
