--------------------------------------------------------
--  Constraints for Table TIPOUTENZADIDATABASE
--------------------------------------------------------

  ALTER TABLE "TIPOUTENZADIDATABASE" MODIFY ("TIPOUTENZADIDATABASE_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOUTENZADIDATABASE" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOUTENZADIDATABASE" ADD CONSTRAINT "TIPOUTENZADIDATABASE_PK" PRIMARY KEY ("TIPOUTENZADIDATABASE_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOUTENZADIDATABASE" ADD CONSTRAINT "TIPOUTENZADIDATABASE_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOUTENZADIDATABASE" ADD CONSTRAINT "TIPOUTENZADIDATABASE_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
