--------------------------------------------------------
--  Constraints for Table TIPOSDL1
--------------------------------------------------------

  ALTER TABLE "TIPOSDL1" MODIFY ("TIPOSDL1_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOSDL1" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOSDL1" ADD CONSTRAINT "TIPOSDL1_PK" PRIMARY KEY ("TIPOSDL1_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOSDL1" ADD CONSTRAINT "TIPOSDL1_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOSDL1" ADD CONSTRAINT "TIPOSDL1_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
