--------------------------------------------------------
--  Constraints for Table TIPOPROCESSINGACTIVITY
--------------------------------------------------------

  ALTER TABLE "TIPOPROCESSINGACTIVITY" MODIFY ("TIPOPROCESSINGACTIVITY_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOPROCESSINGACTIVITY" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOPROCESSINGACTIVITY" ADD CONSTRAINT "TIPOPROCESSINGACTIVITY_PK" PRIMARY KEY ("TIPOPROCESSINGACTIVITY_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOPROCESSINGACTIVITY" ADD CONSTRAINT "TIPOPROCESSINGACTIVITY_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOPROCESSINGACTIVITY" ADD CONSTRAINT "TIPOPROCESSINGACTIVITY_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
