--------------------------------------------------------
--  Constraints for Table TIPOCOMPONENTE
--------------------------------------------------------

  ALTER TABLE "TIPOCOMPONENTE" MODIFY ("TIPOCOMPONENTE_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOCOMPONENTE" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOCOMPONENTE" ADD CONSTRAINT "TIPOCOMPONENTE_PK" PRIMARY KEY ("TIPOCOMPONENTE_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOCOMPONENTE" ADD CONSTRAINT "TIPOCOMPONENTE_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOCOMPONENTE" ADD CONSTRAINT "TIPOCOMPONENTE_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOCOMPONENTE" ADD CONSTRAINT "TIPOCOMPONENTE_UNQ3" UNIQUE ("ORDINE") USING INDEX  ENABLE
