--------------------------------------------------------
--  Constraints for Table TIPOSICUREZZA
--------------------------------------------------------

  ALTER TABLE "TIPOSICUREZZA" MODIFY ("TIPOSICUREZZA_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOSICUREZZA" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOSICUREZZA" ADD CONSTRAINT "TIPOSICUREZZA_PK" PRIMARY KEY ("TIPOSICUREZZA_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOSICUREZZA" ADD CONSTRAINT "TIPOSICUREZZA_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOSICUREZZA" ADD CONSTRAINT "TIPOSICUREZZA_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
