--------------------------------------------------------
--  Constraints for Table TIPOSDL3
--------------------------------------------------------

  ALTER TABLE "TIPOSDL3" MODIFY ("TIPOSDL3_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOSDL3" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOSDL3" ADD CONSTRAINT "TIPOSDL3_PK" PRIMARY KEY ("TIPOSDL3_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOSDL3" ADD CONSTRAINT "TIPOSDL3_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOSDL3" ADD CONSTRAINT "TIPOSDL3_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
