--------------------------------------------------------
--  Constraints for Table TIPOCOMPONENTESERVIZI
--------------------------------------------------------

  ALTER TABLE "TIPOCOMPONENTESERVIZI" MODIFY ("TIPOCOMPONENTESERVIZI_ID" NOT NULL ENABLE)
  ALTER TABLE "TIPOCOMPONENTESERVIZI" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "TIPOCOMPONENTESERVIZI" ADD CONSTRAINT "TIPOCOMPONENTESERVIZI_PK" PRIMARY KEY ("TIPOCOMPONENTESERVIZI_ID") USING INDEX  ENABLE
  ALTER TABLE "TIPOCOMPONENTESERVIZI" ADD CONSTRAINT "TIPOCOMPONENTESERVIZI_UNQ1" UNIQUE ("NAME") USING INDEX  ENABLE
  ALTER TABLE "TIPOCOMPONENTESERVIZI" ADD CONSTRAINT "TIPOCOMPONENTESERVIZI_UNQ2" UNIQUE ("DISPLAYNAME") USING INDEX  ENABLE
