--------------------------------------------------------
--  Constraints for Table UNITAORGANIZZATIVA
--------------------------------------------------------

  ALTER TABLE "UNITAORGANIZZATIVA" MODIFY ("UNITAORGANIZZATIVA_ID" NOT NULL ENABLE)
  ALTER TABLE "UNITAORGANIZZATIVA" MODIFY ("DAPORTAFOGLIO" NOT NULL ENABLE)
  ALTER TABLE "UNITAORGANIZZATIVA" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "UNITAORGANIZZATIVA" ADD CHECK (DAPORTAFOGLIO IN (1,0)) ENABLE
  ALTER TABLE "UNITAORGANIZZATIVA" ADD CHECK (DELETED IN (1,0) OR DELETED IS NULL) ENABLE
  ALTER TABLE "UNITAORGANIZZATIVA" ADD CONSTRAINT "UNITAORGANIZZATIVA_PK" PRIMARY KEY ("UNITAORGANIZZATIVA_ID") USING INDEX  ENABLE
  ALTER TABLE "UNITAORGANIZZATIVA" ADD CONSTRAINT "UNITAORGANIZZATIVA_UNQ1" UNIQUE ("CODICE") USING INDEX  ENABLE
  ALTER TABLE "UNITAORGANIZZATIVA" ADD CONSTRAINT "UNITAORGANIZZATIVA_UNQ2" UNIQUE ("DESCRIZIONE") USING INDEX  ENABLE
