--------------------------------------------------------
--  Constraints for Table UTENTE
--------------------------------------------------------

  ALTER TABLE "UTENTE" MODIFY ("UTENTE_ID" NOT NULL ENABLE)
  ALTER TABLE "UTENTE" MODIFY ("DISABLED" NOT NULL ENABLE)
  ALTER TABLE "UTENTE" MODIFY ("EXPIRED" NOT NULL ENABLE)
  ALTER TABLE "UTENTE" MODIFY ("VERSION" NOT NULL ENABLE)
  ALTER TABLE "UTENTE" ADD CHECK (DELETED IN (1,0) OR DELETED IS NULL) ENABLE
  ALTER TABLE "UTENTE" ADD CHECK (DISABLED IN (1,0)) ENABLE
  ALTER TABLE "UTENTE" ADD CHECK (EXPIRED IN (1,0)) ENABLE
  ALTER TABLE "UTENTE" ADD CONSTRAINT "UTENTE_PK" PRIMARY KEY ("UTENTE_ID") USING INDEX  ENABLE
  ALTER TABLE "UTENTE" ADD CONSTRAINT "UTENTE_UNQ1" UNIQUE ("USERPRINCIPALNAME") USING INDEX  ENABLE
  ALTER TABLE "UTENTE" ADD CONSTRAINT "UTENTE_UNQ2" UNIQUE ("DISTINGUISHNAME") USING INDEX  ENABLE
