--------------------------------------------------------
--  DDL for Table ADSAPPLICAZIONI
--------------------------------------------------------

  CREATE TABLE "ADSAPPLICAZIONI" ("ADS_APPLICAZIONE_ID" NUMBER, "AMMINISTRATOREDISISTEMA_AMMINISTRATOREDISISTEMA_ID_OID" NUMBER, "APPLICAZIONE_APPLICAZIONE_ID_OID" NUMBER, "DATADECORRENZA" DATE, "ORDINE" NUMBER, "VERSION" TIMESTAMP (6))
