--------------------------------------------------------
--  DDL for Table ADSSERVIZITECNICI
--------------------------------------------------------

  CREATE TABLE "ADSSERVIZITECNICI" ("ADS_SERVIZIOTECNICO_ID" NUMBER, "AMMINISTRATOREDISISTEMA_AMMINISTRATOREDISISTEMA_ID_OID" NUMBER, "DATADECORRENZA" DATE, "ORDINE" NUMBER, "SERVIZIOTECNICO_SERVIZIO_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
