--------------------------------------------------------
--  DDL for Table AMMINISTRATOREDISISTEMA
--------------------------------------------------------

  CREATE TABLE "AMMINISTRATOREDISISTEMA" ("AMMINISTRATOREDISISTEMA_ID" NUMBER, "AMBITODEFINITOPUNTUALMENTE" NUMBER(1,0), "ATTIVO" NUMBER(1,0), "DATADECORRENZA" DATE, "DESCRIZIONEAMBITO" VARCHAR2(255), "ELENCODETTAGLIATO" NUMBER(1,0), "RESPONSABILEAPPLICATIVO_RESPONSABILEAPPLICATIVO_ID_OID" NUMBER, "TIPOADSIT" VARCHAR2(255), "VERSION" TIMESTAMP (6))
