--------------------------------------------------------
--  DDL for Table APPLICAZIONIAMBIENTISDLC
--------------------------------------------------------

  CREATE TABLE "APPLICAZIONIAMBIENTISDLC" ("APPLICAZIONE_AMBIENTE_ID" NUMBER, "URIDILANCIO" VARCHAR2(500), "AMBIENTEDISPONIBILE" NUMBER(1,0), "AMBIENTEGESTITO" NUMBER(1,0), "AMBIENTESDLC_AMBIENTESDLC_ID_OID" NUMBER, "APPLICAZIONE_APPLICAZIONE_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
