--------------------------------------------------------
--  DDL for Table APPLICAZIONISERVIZITECNICI
--------------------------------------------------------

  CREATE TABLE "APPLICAZIONISERVIZITECNICI" ("APPLICAZIONE_SERVIZIOTECNICO_ID" NUMBER, "APPLICAZIONE_APPLICAZIONE_ID_OID" NUMBER, "NONPIF9INUSO" NUMBER(1,0), "SERVIZIOTECNICO_SERVIZIO_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
