--------------------------------------------------------
--  DDL for Table APPLICAZIONICOMPARCH
--------------------------------------------------------

  CREATE TABLE "APPLICAZIONICOMPARCH" ("APPLICAZIONE_COMPARCH_ID" NUMBER, "URIREPOSITORY" VARCHAR2(100), "APPLICAZIONE_APPLICAZIONE_ID_OID" NUMBER, "DESCRIZIONE" VARCHAR2(255), "DETTAGLITECNOLOGIASW" VARCHAR2(255), "NONPIF9INUSO" NUMBER(1,0), "TECNOLOGIASW_TECNOLOGIASW_ID_OID" NUMBER, "TIPOCOMPONENTE_TIPOCOMPONENTE_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
