--------------------------------------------------------
--  DDL for Table APPLICAZIONIDATIPERSONALI
--------------------------------------------------------

  CREATE TABLE "APPLICAZIONIDATIPERSONALI" ("APPLICAZIONE_DATI_PERSONALI_ID" NUMBER, "ACCESSOLEGITTIMORISERVATOA" VARCHAR2(255), "APPLICAZIONE_APPLICAZIONE_ID_OID" NUMBER, "CATEGORIADATI_CATEGORIADATI_ID_OID" NUMBER, "CATEGORIAINTERESSATI_CATEGORIAINTERESSATI_ID_OID" NUMBER, "DESCRIZIONE" VARCHAR2(2000), "DESCRIZIONERETENTION" VARCHAR2(500), "MODALITADICONSERVAZIONE" VARCHAR2(500), "NOME" VARCHAR2(255), "RAGIONIPERLACONSERVAZIONEOLTRELARETENTION" VARCHAR2(255), "SOFTWAREUTILIZZATI" VARCHAR2(255), "VERSION" TIMESTAMP (6))
