--------------------------------------------------------
--  DDL for Table ATTIVITA
--------------------------------------------------------

  CREATE TABLE "ATTIVITA" ("ATTIVITA_ID" NUMBER, "ATTIVITAUTENTISERVICE_ATTIVITA_UTENTE_ID_OID" NUMBER, "CONTRATTO_CONTRATTO_ID_OID" NUMBER, "DATADEFINIZIONE" DATE, "DATAINIZIO" DATE, "DATATERMINE" DATE, "DESCRIZIONE" VARCHAR2(255), "TIPOUTENTE_TIPOUTENTETECNICO_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
