--------------------------------------------------------
--  DDL for Table CONTRATTO
--------------------------------------------------------

  CREATE TABLE "CONTRATTO" ("CONTRATTO_ID" NUMBER, "DATAEMISSIONE" DATE, "DATAINIZIOVALIDITA" DATE, "DATATERMINEVALIDITA" DATE, "DESCRIZIONEBREVE" VARCHAR2(255), "DESCRIZIONECOMPLETA" VARCHAR2(3000), "FORNITORE" VARCHAR2(255), "PROTOCOLLO" VARCHAR2(255), "VERSION" TIMESTAMP (6))
