--------------------------------------------------------
--  DDL for Table DATABASEAPPCOMPARCH
--------------------------------------------------------

  CREATE TABLE "DATABASEAPPCOMPARCH" ("DATABASE_APPCOMPARCH_ID" NUMBER, "ADDENDUMTECNICI" VARCHAR2(255), "APPLICAZIONECOMPONENTEARCHITETTURA_APPLICAZIONE_COMPARCH_ID_OID" NUMBER, "DATABASE_DATABASE_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
