--------------------------------------------------------
--  DDL for Table DATABASESERVTECNCOMPARCH
--------------------------------------------------------

  CREATE TABLE "DATABASESERVTECNCOMPARCH" ("DATABASE_SERVTECNCOMPARCH_ID" NUMBER, "ADDENDUMTECNICI" VARCHAR2(255), "DATABASE_DATABASE_ID_OID" NUMBER, "SERVIZIOTECNICOCOMPONENTEARCHITETTURA_SERVIZIOTECNICO_COMPONENTE_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
