--------------------------------------------------------
--  DDL for Table DATABASE
--------------------------------------------------------

  CREATE TABLE "DATABASE" ("DATABASE_ID" NUMBER, "AMBIENTESDLC_AMBIENTESDLC_ID_OID" NUMBER, "ATTIVO" NUMBER(1,0), "DESCRIZIONE" VARCHAR2(255), "DETTAGLITECNICI" VARCHAR2(1000), "FINESTRAMANUTENZIONE" VARCHAR2(255), "NAME" VARCHAR2(255), "SERVER_SERVER_ID_OID" NUMBER, "SERVICENAME" VARCHAR2(255), "TECHDATABASE_TECHDATABASE_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
