--------------------------------------------------------
--  DDL for Table FUNZIONESA
--------------------------------------------------------

  CREATE TABLE "FUNZIONESA" ("FUNZIONESA_ID" NUMBER, "APPLICAZIONESICUREZZAAPPLICATIVA_APPLICAZIONESA_ID_OID" NUMBER, "DATADELETED" DATE, "DELETED" NUMBER(1,0), "DISPLAYNAME" VARCHAR2(255), "FUNZIONESASUP_FUNZIONESA_ID_OID" NUMBER, "NAME" VARCHAR2(255), "TIPOFUNZIONE" VARCHAR2(255), "VERSION" TIMESTAMP (6))
