--------------------------------------------------------
--  DDL for Table GRUPPO
--------------------------------------------------------

  CREATE TABLE "GRUPPO" ("GRUPPO_ID" NUMBER, "CHANGED" DATE, "CREATED" DATE, "DATADELETED" DATE, "DELETED" NUMBER(1,0), "DESCRIZIONE" VARCHAR2(255), "DISTINGUISHEDNAME" VARCHAR2(1000), "IDHISTORY" VARCHAR2(255), "MEMBERS" VARCHAR2(4000), "NOME" VARCHAR2(255), "NOTE" VARCHAR2(255), "OBJECTGUID" VARCHAR2(255), "OBJECTSID" VARCHAR2(255), "ORGANIZATIONUNIT" VARCHAR2(255), "TIPOGRUPPO_TIPOGRUPPO_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
