--------------------------------------------------------
--  DDL for Table IDENTITA
--------------------------------------------------------

  CREATE TABLE "IDENTITA" ("IDENTITA_ID" NUMBER, "CODICEANAGRAFICO" VARCHAR2(255), "DATADEFINIZIONE" DATE, "DATADELETED" DATE, "DATAEXPIRED" DATE, "DELETED" NUMBER(1,0), "DISABLED" NUMBER(1,0), "EXPIRED" NUMBER(1,0), "NOME" VARCHAR2(255), "TIPOIDENTITA_TIPOIDENTITA_ID_OID" NUMBER, "UNITAORGANIZZATIVA_UNITAORGANIZZATIVA_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
