--------------------------------------------------------
--  DDL for Table PIATTAFORMA
--------------------------------------------------------

  CREATE TABLE "PIATTAFORMA" ("PIATTAFORMA_ID" NUMBER, "AMBIENTESDLC_AMBIENTESDLC_ID_OID" NUMBER, "ATTIVO" NUMBER(1,0), "DESCRIZIONE" VARCHAR2(1000), "INFRASTRUTTURAASUPPORTO_TIPOINFRASTRUTTURAASUPPORTO_ID_OID" NUMBER, "NOME" VARCHAR2(255), "TIPOASSET" VARCHAR2(255), "VERSION" TIMESTAMP (6))
