--------------------------------------------------------
--  DDL for Table PIATTAFAPPCOMPARCH
--------------------------------------------------------

  CREATE TABLE "PIATTAFAPPCOMPARCH" ("PIATTAF_APPCOMPARCH_ID" NUMBER, "ADDENDUMTECNICI" VARCHAR2(255), "APPLICAZIONECOMPONENTEARCHITETTURA_APPLICAZIONE_COMPARCH_ID_OID" NUMBER, "PIATTAFORMA_PIATTAFORMA_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
