--------------------------------------------------------
--  DDL for Table PIATTAFSERVTECNCOMPARCH
--------------------------------------------------------

  CREATE TABLE "PIATTAFSERVTECNCOMPARCH" ("PIATTAF_SERVTECNCOMPARCH_ID" NUMBER, "ADDENDUMTECNICI" VARCHAR2(255), "PIATTAFORMA_PIATTAFORMA_ID_OID" NUMBER, "SERVIZIOTECNICOCOMPONENTEARCHITETTURA_SERVIZIOTECNICO_COMPONENTE_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
