--------------------------------------------------------
--  DDL for Table RECORDOFPROCESSINGACTIVITY
--------------------------------------------------------

  CREATE TABLE "RECORDOFPROCESSINGACTIVITY" ("ROPA_ID" NUMBER, "CODICE" VARCHAR2(255), "DATAATTIVITA" DATE, "DATAINIZIO" DATE, "DATATERMINE" DATE, "DESCRIZIONE" VARCHAR2(255), "DETTAGLI" VARCHAR2(4000), "ESITO" NUMBER(1,0), "FILETXTMIMETYPE" VARCHAR2(255), "FILETXTNAME" VARCHAR2(255), "ROPARIGATESTOSERVICE_ROPA_RIGATESTO_ID_OID" NUMBER, "STATO" VARCHAR2(255), "TIPOROPA_TIPOPROCESSINGACTIVITY_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
