--------------------------------------------------------
--  DDL for Table SERVIZITECNICISERVTEC
--------------------------------------------------------

  CREATE TABLE "SERVIZITECNICISERVTEC" ("SERVIZIOTECNICO_SERVTEC_ID" NUMBER, "NONPIF9INUSO" NUMBER(1,0), "SERVIZIOTECNICO_SERVIZIO_ID_OID" NUMBER, "SERVIZIOTECNICOREF_SERVIZIO_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
