--------------------------------------------------------
--  DDL for Table SERVIZITECNICIENDPOINTS
--------------------------------------------------------

  CREATE TABLE "SERVIZITECNICIENDPOINTS" ("SERVIZIOTECNICO_ENDPOINT_ID" NUMBER, "DESCRIZIONE" VARCHAR2(255), "ENDPOINT" VARCHAR2(255), "NONPIUINUSO" NUMBER(1,0), "SERVIZIOTECNICO_SERVIZIO_ID_OID" NUMBER, "TIPOENDPOINT_TIPOENDPOINTSERVIZI_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
