--------------------------------------------------------
--  DDL for Table SERVIZITECNICIAMBIENTISDLC
--------------------------------------------------------

  CREATE TABLE "SERVIZITECNICIAMBIENTISDLC" ("SERVIZIOTECNICO_AMBIENTE_ID" NUMBER, "URIDILANCIO" VARCHAR2(500), "AMBIENTEDISPONIBILE" NUMBER(1,0), "AMBIENTEGESTITO" NUMBER(1,0), "AMBIENTESDLC_AMBIENTESDLC_ID_OID" NUMBER, "SERVIZIOTECNICO_SERVIZIO_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
