--------------------------------------------------------
--  DDL for Table SERVER
--------------------------------------------------------

  CREATE TABLE "SERVER" ("SERVER_ID" NUMBER, "AMBIENTESDLC_AMBIENTESDLC_ID_OID" NUMBER, "ATTIVO" NUMBER(1,0), "CORE" VARCHAR2(255), "DATADEFINIZIONE" DATE, "DATADISMISSIONE" DATE, "DESCRIZIONE" VARCHAR2(255), "DISMESSO" NUMBER(1,0), "FINESTRAMANUTENZIONE" VARCHAR2(255), "HOST" VARCHAR2(255), "INFRASTRUTTURAASUPPORTO_TIPOINFRASTRUTTURAASUPPORTO_ID_OID" NUMBER, "MANAGEMENTIP" VARCHAR2(255), "MANAGEMENTINTERFACE" VARCHAR2(255), "NODONELCLUSTER" VARCHAR2(255), "OPERATIVESYSTEM" VARCHAR2(255), "RAM" VARCHAR2(255), "SERVERNAME" VARCHAR2(255), "SERVICEIP" VARCHAR2(255), "SERVICEINTERFACE" VARCHAR2(255), "TIPOSERVER" VARCHAR2(255), "VLANSETTINGS" VARCHAR2(255), "VERSION" TIMESTAMP (6))
