--------------------------------------------------------
--  DDL for Table SERVIZITECNICICOMPARCH
--------------------------------------------------------

  CREATE TABLE "SERVIZITECNICICOMPARCH" ("SERVIZIOTECNICO_COMPONENTE_ID" NUMBER, "URIREPOSITORY" VARCHAR2(100), "DESCRIZIONE" VARCHAR2(255), "DETTAGLITECNOLOGIASW" VARCHAR2(255), "NONPIF9INUSO" NUMBER(1,0), "SERVIZIOTECNICO_SERVIZIO_ID_OID" NUMBER, "TECNOLOGIASW_TECNOLOGIASWSERVIZI_ID_OID" NUMBER, "TIPOCOMPONENTE_TIPOCOMPONENTESERVIZI_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
