--------------------------------------------------------
--  DDL for Table SHARE
--------------------------------------------------------

  CREATE TABLE "SHARE" ("SHARE_ID" NUMBER, "CONTROLTYPE" VARCHAR2(255), "DATADELETED" DATE, "DELETED" NUMBER(1,0), "GRANTS" VARCHAR2(255), "GRUPPO" VARCHAR2(255), "GRUPPOGRANTEE_GRUPPO_ID_OID" NUMBER, "INDUBBIO" NUMBER(1,0), "INHERITED" NUMBER(1,0), "INHERITEDFLAGS" VARCHAR2(255), "NUMEROOGETTI" NUMBER(10,0), "PATH" VARCHAR2(255), "PROFONDITA" NUMBER(10,0), "PROPIETARIO_UNITAORGANIZZATIVA_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
