--------------------------------------------------------
--  DDL for Table TABELLADBDATIPERSONALI
--------------------------------------------------------

  CREATE TABLE "TABELLADBDATIPERSONALI" ("TABELLADBDATIPERSONALI_ID" NUMBER, "APPLICAZIONE_APPLICAZIONE_ID_OID" NUMBER, "DESCRIZIONE" VARCHAR2(255), "NAME" VARCHAR2(255), "ORDER" VARCHAR2(255), "SCRIPT" VARCHAR2(2000), "VERSION" TIMESTAMP (6))
