--------------------------------------------------------
--  DDL for Table TIPOPROCESSINGACTIVITY
--------------------------------------------------------

  CREATE TABLE "TIPOPROCESSINGACTIVITY" ("TIPOPROCESSINGACTIVITY_ID" NUMBER, "CLASSEPROCESSINGACTIVITY" VARCHAR2(255), "DISPLAYNAME" VARCHAR2(255), "ICONA" VARCHAR2(255), "NAME" VARCHAR2(255), "VERSION" TIMESTAMP (6))
