--------------------------------------------------------
--  DDL for Table TIPOUTENTETECNICO
--------------------------------------------------------

  CREATE TABLE "TIPOUTENTETECNICO" ("TIPOUTENTETECNICO_ID" NUMBER, "CONALTIPRIVILEGI" NUMBER(1,0), "DESCRIPTION" VARCHAR2(255), "DISPLAYNAME" VARCHAR2(255), "ICONA" VARCHAR2(255), "NAME" VARCHAR2(255), "PERATTIVITA" NUMBER(1,0), "TIPOUTENTE_TIPOUTENTE_ID_OID" NUMBER, "VERSION" TIMESTAMP (6))
