--------------------------------------------------------
--  DDL for Table TIPOINFRASTRUTTURAASUPP
--------------------------------------------------------

  CREATE TABLE "TIPOINFRASTRUTTURAASUPP" ("TIPOINFRASTRUTTURAASUPPORTO_ID" NUMBER, "DETAILS" VARCHAR2(255), "DISPLAYNAME" VARCHAR2(255), "NAME" VARCHAR2(255), "ORDINE" VARCHAR2(255), "RESPONSABILITARP" NUMBER(1,0), "VERSION" TIMESTAMP (6))
