--------------------------------------------------------
--  DDL for Table TIPOUTENTE
--------------------------------------------------------

  CREATE TABLE "TIPOUTENTE" ("TIPOUTENTE_ID" NUMBER, "CODIFICAREGEXUSERPRINCIPALNAME" VARCHAR2(255), "DEVEAVEREIDENTITA" NUMBER(1,0), "DISPLAYNAME" VARCHAR2(255), "ICONA" VARCHAR2(255), "IDENTITABYCODICEREGEXONUSERPRINCIPALNAME" VARCHAR2(255), "IDENTITADAASSEGNARE" NUMBER(1,0), "IDENTITAPREFIX" VARCHAR2(255), "NAME" VARCHAR2(255), "ORGANIZATIONUNIT" VARCHAR2(255), "TIPOUTENTETECNICODAASSEGNARE" NUMBER(1,0), "UTENTEAPPLICATIVO" NUMBER(1,0), "VERSION" TIMESTAMP (6))
