--------------------------------------------------------
--  DDL for Table TIPOAPPLICAZIONE
--------------------------------------------------------

  CREATE TABLE "TIPOAPPLICAZIONE" ("TIPOAPPLICAZIONE_ID" NUMBER, "AMBIENTISDLCSCM" NUMBER(1,0), "APPLICAZIONEDITERZI" NUMBER(1,0), "COMPONENTISCM" NUMBER(1,0), "CONTRATTOAMIT" NUMBER(1,0), "DISPLAYNAME" VARCHAR2(255), "GOVERNOINFRAAPPLICATIVA" NUMBER(1,0), "ICONA" VARCHAR2(255), "NAME" VARCHAR2(255), "REPOSITORYSCM" NUMBER(1,0), "SOFTWAREANALITYCS" NUMBER(1,0), "VERSIONISCM" NUMBER(1,0), "VERSION" TIMESTAMP (6))
