--------------------------------------------------------
--  DDL for Table TIPOSERVIZIOTECNICO
--------------------------------------------------------

  CREATE TABLE "TIPOSERVIZIOTECNICO" ("TIPOSERVIZIOTECNICO_ID" NUMBER, "DISPLAYNAME" VARCHAR2(255), "GOVERNOINFRAAPPLICATIVA" NUMBER(1,0), "ICONA" VARCHAR2(255), "NAME" VARCHAR2(255), "SERVIZIOTECNICODITERZI" NUMBER(1,0), "SOFTWAREANALITYCS" NUMBER(1,0), "VERSION" TIMESTAMP (6))
