--------------------------------------------------------
--  DDL for Table UNITAORGANIZZATIVA
--------------------------------------------------------

  CREATE TABLE "UNITAORGANIZZATIVA" ("UNITAORGANIZZATIVA_ID" NUMBER, "CODICE" VARCHAR2(255), "DAPORTAFOGLIO" NUMBER(1,0), "DATADELETED" DATE, "DELETED" NUMBER(1,0), "DESCRIZIONE" VARCHAR2(255), "STRUTTURADAPORTAFOGLIO" VARCHAR2(255), "VERSION" TIMESTAMP (6))
