--------------------------------------------------------
--  DDL for Table UTENTE
--------------------------------------------------------

  CREATE TABLE "UTENTE" ("UTENTE_ID" NUMBER, "ACCONTEXPIRES" VARCHAR2(255), "ACCOUNTDISABLED" VARCHAR2(255), "ALTRODAACCOUNTCONTROL" VARCHAR2(255), "COMMONNAME" VARCHAR2(255), "DATADELETED" DATE, "DELETED" NUMBER(1,0), "DISABLED" NUMBER(1,0), "DISPLAYNAME" VARCHAR2(255), "DISTINGUISHNAME" VARCHAR2(255), "EMAILADDRESS" VARCHAR2(255), "EXPIRED" NUMBER(1,0), "IDENTITA_IDENTITA_ID_OID" NUMBER, "LASTLOGON" DATE, "NOPASSWORDEXPIRATION" VARCHAR2(255), "OBJECTGUID" VARCHAR2(255), "ORGANIZATIONUNIT" VARCHAR2(255), "RUOLOUTENTE" VARCHAR2(255), "SAMACCOUNTNAME" VARCHAR2(255), "TIPOUTENTE_TIPOUTENTE_ID_OID" NUMBER, "TIPOUTENTETECNICO_TIPOUTENTETECNICO_ID_OID" NUMBER, "USERACCOUNTCONTROL" VARCHAR2(255), "USERPRINCIPALNAME" VARCHAR2(255), "VERSION" TIMESTAMP (6))
